// meals-meat.js — kjøttoppskrifter
// For å legge til en ny oppskrift: kopier én blokk og endre feltene.
// highProtein: true = > ~25 g protein per porsjon

export const MEAT_MEALS = [

  {
    id: 'kyllinggryte-kikerter',
    name: 'Kyllinggryte med kikerter og tomater',
    type: 'meat',
    highProtein: true,
    allergens: [],
    tags: ['kylling', 'kjøtt', 'gryte', 'kikerter', 'belgfrukter', 'paprika'],
    prepTime: 30,
    difficulty: 'enkel',
    leftoverFriendly: true,
    vegetarianAlternative: 'Kikertgryte med kokosmelk og tomater',
    recipe: {
      servings: 4,
      steps: [
        'Skjær kyllingfilet (600 g) i grove biter, ca. 3×3 cm. Krydre med salt og pepper.',
        'Varm olje (2 ss) i en stor gryte eller høy stekepanne på middels høy varme. Brun kyllingbitene i 2–3 porsjoner – ikke overfyll gryten, da vil kjøttet dampe istedenfor å steke. Stek 3–4 minutter per side til de er gyldenbrune på overflaten. Ta ut og sett til side.',
        'Skru ned til middels varme. Finhakk løk (1 stk) og hvitløk (3 fedd) og stek i samme gryte i 4–5 minutter til løken er myk og blank. Rør inn paprikapulver (2 ts), spisskummen (1 ts) og gjerne litt chili. Stek krydderne i 1 minutt under omrøring til de dufter.',
        'Legg kyllingen tilbake i gryten. Hell over hermetiske tomater (2 bokser à 400 g) og avrent kikerter (400 g). Rør godt, kok opp og skru ned varmen.',
        'La gryten småkoke uten lokk i 20 minutter under jevnlig omrøring. Sausen skal tykne og kyllingen skal være gjennomkokt og mør. Smak til med salt, pepper og eventuelt litt sitronsaft.',
        'Server med kokt fullkornsris, naanbrød eller godt grovbrød. Pynt gjerne med fersk koriander eller persille.',
      ],
    },
    shoppingList: [
      { item: 'Kyllingfilet', search: 'kyllingfilet', amount: '600 g', estimatedPrice: 89, category: 'Kjøtt' },
      { item: 'Kikerter (boks)', search: 'kikerter boks', amount: '400 g', estimatedPrice: 18, category: 'Tørrvarer' },
      { item: 'Hermetiske tomater', search: 'hermetiske tomater', amount: '2 bokser', estimatedPrice: 24, category: 'Tørrvarer' },
      { item: 'Ris (fullkorn)', search: 'fullkornsris', amount: '300 g', estimatedPrice: 22, category: 'Tørrvarer' },
      { item: 'Løk', search: 'løk', amount: '1 stk', estimatedPrice: 5, category: 'Frukt/grønt' },
    ],
  },

  {
    id: 'kjottboller-tomatsaus',
    name: 'Kjøttboller med tomatsaus og pasta',
    type: 'meat',
    highProtein: true,
    allergens: ['gluten', 'egg', 'laktose'],
    tags: ['kjøttboller', 'pasta', 'tomatsaus', 'kjøtt', 'norsk'],
    prepTime: 30,
    difficulty: 'enkel',
    leftoverFriendly: true,
    vegetarianAlternative: 'Linsebuller i tomatsaus med pasta',
    recipe: {
      servings: 4,
      steps: [
        'Ha kjøttdeig (500 g) i en bolle. Tilsett egg (1 stk), brødsmuler (3 ss), salt (1 ts), pepper og gjerne litt muskatnøtt. Bland godt med hendene til jevn konsistens. Form til runde boller på størrelse med en golfball – fukt hendene for å unngå at kjøttet setter seg fast.',
        'Varm olje (2 ss) i en stor stekepanne på middels høy varme. Legg bollene i pannen med god avstand og stek uten å røre i 2–3 minutter til de er brune på undersiden. Rull dem forsiktig og stek videre 2–3 minutter til. De trenger ikke å være gjennomstekte ennå – de skal ettersteke i sausen. Ta dem ut og sett til side.',
        'Finhakk løk (1 stk) og hvitløk (3 fedd). Stek i samme panne på middels varme i 4–5 minutter til mykt. Tilsett hermetiske tomater (2 bokser à 400 g) og riv inn fersk basilikum (halve bunten). Rør godt og smak til med salt, pepper og en klype sukker om sausen er syrlig.',
        'La tomatsausen småkoke i 10 minutter under omrøring. Legg kjøttbollene forsiktig tilbake i sausen og la alt småkoke videre i 10–15 minutter til bollene er gjennomkokte (skjær en i to for å sjekke – ingen rosa kjerne).',
        'Kok fullkornspasta (400 g) etter anvisning mens sausen koker. Spar litt pastavann.',
        'Server pasta toppet med kjøttboller og saus. Riv over parmesan og pynt med resten av basilikumbladene.',
      ],
    },
    shoppingList: [
      { item: 'Kjøttdeig (storfe)', search: 'kjøttdeig storfe', amount: '500 g', estimatedPrice: 65, category: 'Kjøtt' },
      { item: 'Fullkornspasta', search: 'fullkornspasta', amount: '400 g', estimatedPrice: 28, category: 'Tørrvarer' },
      { item: 'Hermetiske tomater', search: 'hermetiske tomater', amount: '2 bokser', estimatedPrice: 24, category: 'Tørrvarer' },
      { item: 'Egg', search: 'egg', amount: '1 stk', estimatedPrice: 4, category: 'Meieri' },
      { item: 'Frisk basilikum', search: 'basilikum fersk', amount: '1 potte', estimatedPrice: 25, category: 'Frukt/grønt' },
    ],
  },

  {
    id: 'tacos-kylling',
    name: 'Tacosfredag med kylling og hjemmelaget salsa',
    type: 'meat',
    highProtein: true,
    allergens: ['gluten', 'laktose'],
    tags: ['tacos', 'kylling', 'kjøtt', 'fredag', 'meksikansk', 'salsa'],
    prepTime: 25,
    difficulty: 'enkel',
    leftoverFriendly: false,
    vegetarianAlternative: 'Tacos med svarte bønner, mais og avokado',
    recipe: {
      servings: 4,
      steps: [
        'Skjær kyllingstrimler (500 g) i jevne strimler. Bland i en bolle med spisskummen (1 ts), røkt paprika (1 ts), chilipulver (½ ts) og salt (1 ts). Vend godt slik at alle strimlene er dekket med krydder.',
        'Varm olje (2 ss) i en stekepanne på høy varme til den er virkelig varm – krydderkylling trenger høy temperatur for å karamellisere. Legg strimlene i pannen i ett lag (stek i to porsjoner om nødvendig) og stek 4–5 minutter uten å røre for å få en fin stekeskorpe. Rør og stek 3–4 minutter til til kyllingen er gjennomstekt. Den skal ha litt svidd, mørk kantete.',
        'Lag hjemmelaget salsa: hakk tomat (3 stk) fint, finhakk rødløk (½ stk) og koriander (en god håndfull). Bland i en bolle med saften av ½ lime, salt og en klype sukker. La stå 10 minutter så smakene setter seg.',
        'Del avokado (2 stk) i to, fjern steinen, og skjær i skiver eller mos med litt limesaft og salt til guacamole.',
        'Forvarm tortillalefsene: legg dem direkte på gassbrenneren på medium flamme og snu etter 20–30 sekunder (de skal få litt sviskede kanter), eller varm 2 minutter i ovn på 180 °C. Alternativt: varm tørr panne, 30 sekunder per side.',
        'Sett frem kyllingstrimler, salsa, avokado/guacamole, rømme og revet salat i boller slik at alle kan bygge sine egne tacos.',
      ],
    },
    shoppingList: [
      { item: 'Kyllingstrimler', search: 'kyllingstrimler', amount: '500 g', estimatedPrice: 79, category: 'Kjøtt' },
      { item: 'Tortillalefser', search: 'tortilla lefse', amount: '8 stk', estimatedPrice: 28, category: 'Tørrvarer' },
      { item: 'Tomat', search: 'tomat', amount: '3 stk', estimatedPrice: 18, category: 'Frukt/grønt' },
      { item: 'Avokado', search: 'avokado', amount: '2 stk', estimatedPrice: 30, category: 'Frukt/grønt' },
      { item: 'Rømme', search: 'rømme', amount: '1 dl', estimatedPrice: 22, category: 'Meieri' },
    ],
  },

  {
    id: 'bolognese',
    name: 'Spagetti bolognese',
    type: 'meat',
    highProtein: true,
    allergens: ['gluten', 'laktose'],
    tags: ['bolognese', 'pasta', 'kjøttdeig', 'kjøtt', 'italiensk'],
    prepTime: 40,
    difficulty: 'enkel',
    leftoverFriendly: true,
    vegetarianAlternative: 'Linsebolognese med fullkornspasta',
    recipe: {
      servings: 4,
      steps: [
        'Finhakk løk (1 stor) og hvitløk (3 fedd). Skrell og hakk gulrot (1 stk) og selleri (1 stilk) i svært fine biter – disse er grunnsausen (soffritto).',
        'Varm olje (2 ss) i en bred, tung kjele på middels varme. Stek løk, gulrot og selleri i 8–10 minutter under jevnlig omrøring til grønnsakene er myke og søte. Tilsett hvitløk og stek 1 minutt til.',
        'Skru opp varmen til høy. Tilsett kjøttdeig (400 g) og brun den grundig i 5–8 minutter. Bruk en stekespade til å bryte opp kjøttet i fine smuler. La det ligge uten å røre mellom omrøringene – kjøttet skal steke, ikke dampe. Det er ferdig brunet når det er gråbrunt uten rosa kjerne.',
        'Hell i tomatpuré (2 ss) og rør inn i kjøttet. La surre 2 minutter. Tilsett hermetiske tomater (2 bokser à 400 g), rør godt og kok opp.',
        'Skru ned til svak varme. La bolognesen småkoke uten lokk i 25–30 minutter under jevnlig røring. Sausen skal tykne og bli konsentrert. Smak til med salt, pepper og gjerne en klype sukker. Riv inn fersk basilikum om du har.',
        'Kok fullkornsspagetti (400 g) etter anvisning. Spar 1 dl pastavann. Bland pastaen med litt av sausen og pastavann i kjelen for å binde alt sammen. Server med resten av sausen over og rikelig med revet parmesan.',
      ],
    },
    shoppingList: [
      { item: 'Kjøttdeig (storfe)', search: 'kjøttdeig storfe', amount: '400 g', estimatedPrice: 55, category: 'Kjøtt' },
      { item: 'Spagetti (fullkorn)', search: 'fullkornsspagetti', amount: '400 g', estimatedPrice: 28, category: 'Tørrvarer' },
      { item: 'Hermetiske tomater', search: 'hermetiske tomater', amount: '2 bokser', estimatedPrice: 24, category: 'Tørrvarer' },
      { item: 'Tomatpuré', search: 'tomatpuré', amount: '2 ss', estimatedPrice: 6, category: 'Tørrvarer' },
      { item: 'Parmesan', search: 'parmesan', amount: '50 g', estimatedPrice: 32, category: 'Meieri' },
    ],
  },

  {
    id: 'kyllingwok',
    name: 'Kyllingwok med grønnsaker og ris',
    type: 'meat',
    highProtein: true,
    allergens: ['soya', 'gluten', 'sesam'],
    tags: ['kylling', 'wok', 'asiatisk', 'ris', 'kjøtt', 'rask'],
    prepTime: 25,
    difficulty: 'enkel',
    leftoverFriendly: true,
    vegetarianAlternative: 'Tofuwok med grønnsaker og ris',
    recipe: {
      servings: 4,
      steps: [
        'Start risen (300 g basmati) etter anvisning – den tar lengst tid. Skyll risen til vannet er klart, kok opp med dobbelt mengde vann og salt, skru ned og la trekke med lokk i 12 minutter. Skru av og la hvile 10 minutter.',
        'Skjær kyllingfilet (500 g) i tynne strimler på tvers av muskelfibrene – dette gir mørere biter. Bland med salt, pepper og litt soyasaus (1 ss) og la marinere mens du forbereder grønnsakene.',
        'Del brokkolien (1 hode) i små buketter, skjær paprika (2 stk) i strimler og mål opp sukkererter (100 g). Finhakk hvitløk (2 fedd) og fersk ingefær (2 cm).',
        'Varm en wok eller stor stekepanne på absolutt høyeste varme til den ryker. Tilsett olje (2 ss) og legg i kyllingstrimlene. Stek 4–5 minutter uten å røre for å få god bruning. Rør og stek til kyllingen er gjennomstekt og har fin farge. Ta ut og sett til side.',
        'Ha i litt mer olje om nødvendig. Stek hvitløk og ingefær i 30 sekunder. Tilsett brokkoli og paprika og wok på høy varme i 2–3 minutter – grønnsakene skal bli lyse og sprø, ikke kokte. Legg i sukkererter og stek 1 minutt til.',
        'Legg kyllingen tilbake. Tilsett soyasaus (2 ss) og sesamolje (1 ts) – ikke mer, sesamolje har intens smak. Rør alt godt sammen og server umiddelbart over risen. Dryss over sesamfrø om du har.',
      ],
    },
    shoppingList: [
      { item: 'Kyllingfilet', search: 'kyllingfilet', amount: '500 g', estimatedPrice: 79, category: 'Kjøtt' },
      { item: 'Basmatiris', search: 'basmatiris', amount: '300 g', estimatedPrice: 22, category: 'Tørrvarer' },
      { item: 'Paprika (rød)', search: 'paprika rød', amount: '2 stk', estimatedPrice: 20, category: 'Frukt/grønt' },
      { item: 'Brokkoli', search: 'brokkoli', amount: '1 hode', estimatedPrice: 25, category: 'Frukt/grønt' },
      { item: 'Soyasaus', search: 'soyasaus', amount: '3 ss', estimatedPrice: 8, category: 'Tørrvarer' },
    ],
  },

  {
    id: 'kyllingsuppe',
    name: 'Kyllingsuppe med grønnsaker og nudler',
    type: 'meat',
    highProtein: false,
    allergens: ['gluten', 'selleri'],
    tags: ['kylling', 'suppe', 'kjøtt', 'nudler', 'norsk'],
    prepTime: 35,
    difficulty: 'enkel',
    leftoverFriendly: true,
    vegetarianAlternative: 'Grønnsakssuppe med eggnudler',
    recipe: {
      servings: 4,
      steps: [
        'Ha kyllingbuljong (2 terninger) i 1,5 l kokende vann og rør til det løser seg opp, eller bruk hjemmelaget kyllingkraft om du har.',
        'Legg kyllingfilet (400 g) hel i den kokende kraften. Skru ned varmen til suppen trekker uten å koke kraftig – for høy varme gjør kyllingen seig. La trekke i 15–18 minutter til kyllingen er gjennomkokt (skjær i den tykkeste delen – ingen rosa kjerne). Ta ut kyllingen og la den avkjøles litt.',
        'Mens kyllingen trekker: skjær gulrot (3 stk) i skiver og selleri (3 stilker) i biter.',
        'Bruk to gafler til å rive kyllingen i grove tråder – dette gir langt bedre tekstur i suppen enn å kutte den.',
        'Legg gulrot og selleri i kraften og kok 5 minutter. Tilsett eggnudler (200 g) og kok videre 4–5 minutter til nudlene er møre og grønnsakene er kokte.',
        'Legg den revne kyllingen tilbake i suppen og varm opp. Smak til med salt, pepper og gjerne litt sitronsaft. Server med hakket fersk persille over.',
      ],
    },
    shoppingList: [
      { item: 'Kyllingfilet', search: 'kyllingfilet', amount: '400 g', estimatedPrice: 69, category: 'Kjøtt' },
      { item: 'Gulrot', search: 'gulrot', amount: '3 stk', estimatedPrice: 12, category: 'Frukt/grønt' },
      { item: 'Selleri', search: 'selleri stilk', amount: '3 stilker', estimatedPrice: 12, category: 'Frukt/grønt' },
      { item: 'Eggnudler', search: 'eggnudler', amount: '200 g', estimatedPrice: 22, category: 'Tørrvarer' },
      { item: 'Kyllingbuljong', search: 'kyllingbuljong', amount: '2 terninger', estimatedPrice: 6, category: 'Tørrvarer' },
    ],
  },

  {
    id: 'svinekoteletter-eple',
    name: 'Svinekoteletter med eple, løk og potet',
    type: 'meat',
    highProtein: true,
    allergens: ['laktose'],
    tags: ['svin', 'koteletter', 'kjøtt', 'norsk', 'eple', 'høst'],
    prepTime: 35,
    difficulty: 'enkel',
    leftoverFriendly: false,
    vegetarianAlternative: 'Ovnsbakt rotgrønnsaksgrateng med eple',
    recipe: {
      servings: 4,
      steps: [
        'Forvarm ovnen til 200 °C. Skrubb poteter (600 g), legg i en kjele med kaldt saltet vann og kok i 15 minutter til nesten møre. Hell av.',
        'Tørk svinekotelettene (4 stk) grundig med kjøkkenpapir. Krydre godt med salt og pepper på begge sider. Varm olje (1 ss) i en ovnssikker stekepanne på høy varme og brun kotelettene 2 minutter per side til de har fin stekeskorpe. Ta ut og sett til side.',
        'Skjær eple (2 stk, fast sort som Granny Smith eller Aroma) i tykke ringer og fjern kjernen. Skjær løk (2 stk) i halvmåner. Stek eple og løk i samme panne på middels varme i 4–5 minutter til lett karamellisert.',
        'Legg kotelettene tilbake i pannen over eple og løk, og sett hele pannen i ovnen. Stek 12–15 minutter til kotelettene er gjennomstekte – stikk et steketermometer i den tykkeste delen, det skal vise 71 °C, eller skjær inn og sjekk at det ikke er rosa lenger.',
        'Mos potetene grovt eller server hele. Smak til med salt og eventuelt litt smør.',
        'Server kotelettene med eple og løk på toppen og poteter ved siden av. Legg en klatt rømme ved siden av.',
      ],
    },
    shoppingList: [
      { item: 'Svinekoteletter', search: 'svinekoteletter', amount: '4 stk (ca. 600 g)', estimatedPrice: 75, category: 'Kjøtt' },
      { item: 'Eple (fast sort)', search: 'eple', amount: '2 stk', estimatedPrice: 14, category: 'Frukt/grønt' },
      { item: 'Løk', search: 'løk', amount: '2 stk', estimatedPrice: 8, category: 'Frukt/grønt' },
      { item: 'Potet', search: 'potet', amount: '600 g', estimatedPrice: 18, category: 'Frukt/grønt' },
      { item: 'Rømme', search: 'rømme', amount: '1 dl', estimatedPrice: 15, category: 'Meieri' },
    ],
  },

  {
    id: 'karbonader',
    name: 'Karbonader med surkål og potetmos',
    type: 'meat',
    highProtein: true,
    allergens: ['gluten', 'egg', 'laktose'],
    tags: ['karbonader', 'kjøtt', 'norsk', 'surkål', 'potetmos', 'tradisjonell'],
    prepTime: 35,
    difficulty: 'enkel',
    leftoverFriendly: false,
    vegetarianAlternative: 'Vegetarbuller med surkål og potetmos',
    recipe: {
      servings: 4,
      steps: [
        'Skjær poteter (700 g) i jevne biter, legg i en kjele og dekk med kaldt saltet vann. Kok opp og la koke i 15–20 minutter til de er møre hele veien gjennom – stikk med en kniv, det skal ikke gi motstand.',
        'Mens potetene koker: finhakk løk (½ stk). Ha kjøttdeig (500 g) i en bolle og bland godt med hakket løk, egg (1 stk), salt (1 ts), pepper og gjerne litt allehånde. Ikke overjobb kjøttet – bare bland til jevnt. Form til flate, runde kaker ca. 1,5 cm tykke og 8–9 cm i diameter.',
        'Varm smør (1 ss) i en stekepanne på middels varme. Legg karbonadene i pannen og stek 4–5 minutter per side. De skal være gjennomstekte og ha en fin gyllen skorpe – skjær inn i en for å sjekke at det ikke er rosa kjerne.',
        'Hell av potetvannet og la potetene dampe ut litt i kjelen. Tilsett smør (50 g) og varm melk (1 dl) – start med litt og tilsett mer om nødvendig. Mos til jevn og luftig konsistens med en potetstamper eller potetpresse. Smak til med salt, pepper og gjerne litt muskatnøtt.',
        'Varm surkål (400 g) i en liten kjele på svak varme. Smak til – om den er veldig syrlig kan du tilsette en liten klype sukker.',
        'Server karbonadene med et godt lag potetmos og surkål ved siden av. Smøret som smelter fra karbonadene er en naturlig saus.',
      ],
    },
    shoppingList: [
      { item: 'Kjøttdeig (svin/storfe)', search: 'kjøttdeig', amount: '500 g', estimatedPrice: 55, category: 'Kjøtt' },
      { item: 'Potet', search: 'potet', amount: '700 g', estimatedPrice: 20, category: 'Frukt/grønt' },
      { item: 'Surkål (boks)', search: 'surkål', amount: '400 g', estimatedPrice: 22, category: 'Tørrvarer' },
      { item: 'Smør', search: 'smør', amount: '75 g', estimatedPrice: 18, category: 'Meieri' },
      { item: 'Melk', search: 'melk', amount: '1 dl', estimatedPrice: 4, category: 'Meieri' },
    ],
  },

  {
    id: 'pulled-chicken-wrap',
    name: 'Pulled chicken wrap med coleslaw',
    type: 'meat',
    highProtein: true,
    allergens: ['gluten', 'egg', 'sennep'],
    tags: ['kylling', 'wrap', 'pulled', 'kjøtt', 'coleslaw'],
    prepTime: 40,
    difficulty: 'enkel',
    leftoverFriendly: true,
    vegetarianAlternative: 'Pulled jackfruit wrap med coleslaw',
    recipe: {
      servings: 4,
      steps: [
        'Legg kyllingfilet (600 g) i en kjele og dekk med vann. Tilsett paprikapulver (2 ts), løkpulver (1 ts), chilipulver (½ ts) og salt (1 ts). Kok opp og la trekke på middels varme i 20–25 minutter til kyllingen er gjennomkokt og veldig mør.',
        'Ta ut kyllingen og la den avkjøles litt slik at du tåler å håndtere den. Bruk to gafler og riv kyllingen i lange, tynne tråder. Bland de revne trådene med 2–3 ss av kokevannet (nå en smaksrik kraft) for å holde kyllingen saftig.',
        'Lag coleslaw: del ¼ hvittkål i tynne strimler (eller bruk en mandolin). Rasp gulrot (2 stk) grovt. Bland kål og gulrot i en bolle med majones (3–4 ss), hvitvinseddik (1 ss), salt, pepper og en klype sukker. Smak til. La coleslawet stå minst 10 minutter slik at kålen mykner litt i dressingen.',
        'Varm tortillalefsene: legg dem direkte på en varm tørr stekepanne, 20–30 sekunder per side til de er varme og litt puffete. Hold varme under et kjøkkenhåndkle.',
        'Legg ut lefsene og fordel pulled chicken, coleslaw og gjerne litt sriracha eller annen sterk saus i en stripe på midten. Brett inn sidene og rull tett.',
        'Server umiddelbart, gjerne skåret på skrå. Ekstra coleslaw kan stå ved siden av.',
      ],
    },
    shoppingList: [
      { item: 'Kyllingfilet', search: 'kyllingfilet', amount: '600 g', estimatedPrice: 89, category: 'Kjøtt' },
      { item: 'Tortillalefser', search: 'tortilla lefse', amount: '8 stk', estimatedPrice: 28, category: 'Tørrvarer' },
      { item: 'Hvittkål', search: 'hvittkål', amount: '¼ hode', estimatedPrice: 10, category: 'Frukt/grønt' },
      { item: 'Gulrot', search: 'gulrot', amount: '2 stk', estimatedPrice: 8, category: 'Frukt/grønt' },
      { item: 'Majones', search: 'majones', amount: '3 ss', estimatedPrice: 10, category: 'Tørrvarer' },
    ],
  },

  {
    id: 'kylling-tikka',
    name: 'Kylling tikka masala med naanbrød',
    type: 'meat',
    highProtein: true,
    allergens: ['gluten', 'laktose'],
    tags: ['kylling', 'indisk', 'tikka', 'kjøtt', 'krydret', 'curry'],
    prepTime: 40,
    difficulty: 'avansert',
    leftoverFriendly: true,
    vegetarianAlternative: 'Paneer tikka masala med naanbrød',
    recipe: {
      servings: 4,
      steps: [
        'Skjær kyllingfilet (600 g) i biter på ca. 4×4 cm. Bland gresk yoghurt (1 dl) med tikka masala-krydder (1 ss), salt og litt sitronsaft. Vend kyllingen i marinaden og la stå minst 30 minutter – gjerne over natten i kjøleskap for dypere smak.',
        'Varm olje (2 ss) i en stor stekepanne på høy varme. Stek kyllingbitene i 2 porsjoner – ikke overfyll – i 3–4 minutter per side til de er karamelliserte og mørke i kantene. Det er OK om de ikke er helt gjennomstekte ennå, de etterkoker i sausen. Ta ut og sett til side.',
        'Finhakk løk (1 stk) og hvitløk (3 fedd), riv ingefær (2 cm). Stek i samme panne på middels varme i 5–6 minutter til løken er myk og gyllen. Tilsett tikka masala-krydder (1 ss til) og stek 1–2 minutter under omrøring til krydderne dufter og steker seg – dette er avgjørende for smaken.',
        'Tilsett hermetiske tomater (1 boks) og rør godt. La surre 5 minutter. Tilsett matfløte (2 dl) og rør inn. Kok opp og smak til med salt – sausen skal være fyldig og litt krydret.',
        'Legg kyllingbitene tilbake i sausen og la alt småkoke på middels svak varme i 10 minutter til kyllingen er helt gjennomstekt og sausen er tyknet. Rør jevnlig.',
        'Varm naanbrød (4 stk) i en tørr stekepanne, 1 minutt per side, eller i ovn på 180 °C i 5 minutter. Server tikka masalaen med basmatiris og naanbrød. Pynt med fersk koriander.',
      ],
    },
    shoppingList: [
      { item: 'Kyllingfilet', search: 'kyllingfilet', amount: '600 g', estimatedPrice: 89, category: 'Kjøtt' },
      { item: 'Tikka masala-krydder', search: 'tikka masala krydder', amount: '2 ss', estimatedPrice: 12, category: 'Tørrvarer' },
      { item: 'Matfløte', search: 'matfløte', amount: '2 dl', estimatedPrice: 28, category: 'Meieri' },
      { item: 'Gresk yoghurt', search: 'gresk yoghurt', amount: '1 dl', estimatedPrice: 15, category: 'Meieri' },
      { item: 'Naanbrød', search: 'naanbrød', amount: '4 stk', estimatedPrice: 28, category: 'Tørrvarer' },
    ],
  },

  // ── MIDDELS KOMPLEKSE OPPSKRIFTER ─────────────────────────────────────────

  {
    id: 'biff-rodvinssaus',
    name: 'Biff med rødvinssaus og gratinerte poteter',
    type: 'meat',
    highProtein: true,
    allergens: ['laktose', 'selleri'],
    tags: ['biff', 'kjøtt', 'rødvin', 'grateng', 'potet', 'festmat', 'norsk', 'helg'],
    prepTime: 55,
    difficulty: 'middels',
    leftoverFriendly: false,
    vegetarianAlternative: 'Portobellosopp med rødvinssaus og gratinerte poteter',
    recipe: {
      servings: 4,
      steps: [
        'Lag gratinerte poteter: forvarm ovnen til 190 °C. Skjær poteter (800 g, faste) i tynne skiver (ca. 3 mm). Smør en ildfast form (20×30 cm) med smør. Legg potetskivene i overlappende lag, salt og pepper mellom hvert lag. Bland kremfløte (3 dl) med hvitløk (2 fedd, presset) og hell jevnt over. Dekk med folie og stek 30 minutter, fjern folie og stek videre 15–20 minutter til toppen er gyllen og potetene møre.',
        'Lag rødvinssaus: finhakk sjalottløk (2 stk) og selleri (1 stilk). Stek i smør (1 ss) i en liten kjele 3–4 minutter til mykt. Hell over rødvin (2 dl) og la koke inn til halvparten (ca. 5 minutter). Tilsett oksekraft (2 dl) og timian (2 kvister). La småkoke 10 minutter. Sil sausen, rør inn kald smør (2 ss) til glatt og blank. Smak til med salt og pepper.',
        'Ta biffene (4 stk à ca. 200 g, entrecôte eller indrefilet) ut av kjøleskap 30 minutter før steking – romtemperatur gir jevnere steking. Tørk godt med kjøkkenpapir og krydre med salt og pepper like før steking.',
        'Varm en tung stekepanne (gjerne støpejern) til den ryker. Tilsett nøytral olje (1 ss). Legg biffene i pannen – de skal syde kraftig. Stek 2–3 minutter per side for medium rare (kjernetemperatur 55–58 °C). Legg til en god klatt smør, timiankvister og hvitløk de siste minuttet, og øs det smeltede smøret over biffene.',
        'La biffene hvile på et fjøl i minst 5 minutter. Skjær langs muskelfibrene for størst mørhet.',
        'Server biff med rødvinssaus slått over, gratinerte poteter ved siden av og en enkel grønn salat eller haricot verts.',
      ],
    },
    shoppingList: [
      { item: 'Entrecôte (4 stk)', search: 'entrecôte biff', amount: '800 g', estimatedPrice: 249, category: 'Kjøtt' },
      { item: 'Potet (fast sort)', search: 'potet fast', amount: '800 g', estimatedPrice: 22, category: 'Frukt/grønt' },
      { item: 'Kremfløte', search: 'kremfløte', amount: '3 dl', estimatedPrice: 35, category: 'Meieri' },
      { item: 'Rødvin', search: 'rødvin', amount: '2 dl', estimatedPrice: 45, category: 'Diverse' },
      { item: 'Smør', search: 'smør', amount: '100 g', estimatedPrice: 22, category: 'Meieri' },
    ],
  },

  {
    id: 'lammelaar-ovn',
    name: 'Lammelår i ovn med hvitløk og rosmarin',
    type: 'meat',
    highProtein: true,
    allergens: ['selleri'],
    tags: ['lam', 'kjøtt', 'ovn', 'rosmarin', 'hvitløk', 'festmat', 'påske', 'helg'],
    prepTime: 120,
    difficulty: 'middels',
    leftoverFriendly: true,
    vegetarianAlternative: 'Ovnsbakt blomkålstek med urteolje',
    recipe: {
      servings: 6,
      steps: [
        'Ta lammelåret (ca. 2 kg) ut av kjøleskap 1 time før steking. Forvarm ovnen til 220 °C.',
        'Skjær 15–20 dype lommer over hele kjøttstykket med en skarp kniv. Stapp inn hvitløkfedd (5–6 fedd, delt i to) og rosmarinkvister i hvert snitt. Gni hele overflaten med olivenolje (3 ss), salt og pepper.',
        'Legg lammelåret i en langpanne oppå grovt hakkede grønnsaker: gulrot (2 stk), løk (1 stk) og selleri (2 stk) som naturlig grønnsaksseng. Hell rødvin (2 dl) og lammekraft (2 dl) i bunnen av pannen.',
        'Sett i ovnen på 220 °C i 15 minutter for å brune overflaten. Skru ned til 170 °C og stek videre 1 time og 15 minutter for rosa lam (kjernetemperatur 60–63 °C) eller 1 time 30 minutter for gjennomstekt (70 °C). Øs kjøttkraft over lammeet hvert 30. minutt.',
        'Ta lammeet ut og la hvile under folie i minst 20 minutter – dette er avgjørende for mørheten. Resterende temperatur vil fortsette å stige ca. 5 °C.',
        'Lag saus av stekesjyene: sil grønnsakene fra pannen, skum av fett og kok inn til ca. halvparten. Smak til med salt og pepper. Skjær lammelåret i skiver og server med lammesaus, ovnsbakte poteter og grønnsaker.',
      ],
    },
    shoppingList: [
      { item: 'Lammelår (benfritt)', search: 'lammelår', amount: 'ca. 2 kg', estimatedPrice: 299, category: 'Kjøtt' },
      { item: 'Hvitløk', search: 'hvitløk', amount: '1 hode', estimatedPrice: 8, category: 'Frukt/grønt' },
      { item: 'Fersk rosmarin', search: 'rosmarin fersk', amount: '4 kvister', estimatedPrice: 12, category: 'Frukt/grønt' },
      { item: 'Gulrot', search: 'gulrot', amount: '2 stk', estimatedPrice: 8, category: 'Frukt/grønt' },
      { item: 'Rødvin', search: 'rødvin', amount: '2 dl', estimatedPrice: 45, category: 'Diverse' },
    ],
  },

  // ── EKSISTERENDE NYE OPPSKRIFTER ──────────────────────────────────────────

  {
    id: 'oksegryte-rotgronnsaker',
    name: 'Oksegryte med rotgrønnsaker',
    type: 'meat',
    highProtein: true,
    allergens: ['selleri'],
    tags: ['okse', 'storfe', 'kjøtt', 'gryte', 'rotgrønnsaker', 'norsk', 'høst', 'langkokt'],
    prepTime: 60,
    difficulty: 'enkel',
    leftoverFriendly: true,
    vegetarianAlternative: 'Linse- og rotgrønnsaksgryte med timian',
    recipe: {
      servings: 4,
      steps: [
        'Skjær oksekjøtt til gryte (700 g) i grove biter, ca. 4×4 cm. Tørk godt med kjøkkenpapir og krydre med salt og pepper.',
        'Varm olje (2 ss) i en tung gryte (gjerne støpejern) på høy varme. Brun kjøttet i 2–3 porsjoner, 2–3 minutter per side til godt karamellisert og mørkebrunt. Ikke overfyll – dette gir smak. Ta ut og sett til side.',
        'Skru ned til middels varme. Grovhakk løk (2 stk), selleri (2 stilker) og hvitløk (3 fedd). Stek i samme gryte i 5 minutter til mykt. Tilsett tomatpuré (2 ss) og stek 2 minutter under omrøring.',
        'Legg kjøttet tilbake. Hell over oksekraft eller vann (6 dl), laurbærblad (2 stk) og timian (4 kvister). Kok opp, skru ned til svak varme og sett på lokk. La gryten småkoke i 45–50 minutter til kjøttet er mørt.',
        'Skrell og skjær gulrot (3 stk), pastinakk (2 stk) og potet (400 g) i store biter. Legg dem i gryten de siste 20 minuttene. Sjekk at grønnsakene er møre med en kniv.',
        'Smak til med salt og pepper. Fjern laurbærblad og timiankvister. Server med godt grovbrød eller knekkebrød.',
      ],
    },
    shoppingList: [
      { item: 'Oksekjøtt til gryte', search: 'oksekjøtt gryte', amount: '700 g', estimatedPrice: 119, category: 'Kjøtt' },
      { item: 'Gulrot', search: 'gulrot', amount: '3 stk', estimatedPrice: 12, category: 'Frukt/grønt' },
      { item: 'Pastinakk', search: 'pastinakk', amount: '2 stk', estimatedPrice: 18, category: 'Frukt/grønt' },
      { item: 'Potet', search: 'potet', amount: '400 g', estimatedPrice: 15, category: 'Frukt/grønt' },
      { item: 'Tomatpuré', search: 'tomatpuré', amount: '2 ss', estimatedPrice: 6, category: 'Tørrvarer' },
    ],
  },

  {
    id: 'kylling-souvlaki',
    name: 'Kylling souvlaki med tzatziki og pitabrød',
    type: 'meat',
    highProtein: true,
    allergens: ['gluten', 'laktose'],
    tags: ['kylling', 'kjøtt', 'gresk', 'souvlaki', 'tzatziki', 'pita', 'grillmat', 'middelhav'],
    prepTime: 30,
    difficulty: 'enkel',
    leftoverFriendly: false,
    vegetarianAlternative: 'Haloumi souvlaki med tzatziki og pitabrød',
    recipe: {
      servings: 4,
      steps: [
        'Skjær kyllingfilet (600 g) i store biter, ca. 3×3 cm. Bland i en bolle med olivenolje (3 ss), sitronskall og saft fra 1 sitron, hvitløk (2 fedd, presset), oregano (1 ts), salt (1 ts) og pepper. Dekk til og mariner minst 20 minutter – gjerne 1–2 timer i kjøleskap.',
        'Lag tzatziki: riv agurk (½ stk), klem ut overflødig vann godt. Bland med gresk yoghurt (2 dl), presset hvitløk (1 fedd), olivenolje (1 ss), sitronsaft, salt og pepper. La stå i kjøleskap mens du lager resten.',
        'Tre kyllingbitene på trespyd (bløtlegg trispyd i vann 10 min først for å unngå sviing), ca. 4–5 biter per spyd.',
        'Grill på høy varme (grillpanne eller utendørs) i 3–4 minutter per side til kyllingen er gjennomstekt og har grillindikasjoner. Skjær inn i en bit og sjekk – ingen rosa kjerne.',
        'Varm pitabrød (4 stk) direkte på grillen eller i en tørr panne, 30 sekunder per side.',
        'Legg pitabrød på tallerkener, legg kyllingspydene over og fordel tzatziki, rødløkringer, cherrytomater og fersk persille over. Klem litt sitron over alt.',
      ],
    },
    shoppingList: [
      { item: 'Kyllingfilet', search: 'kyllingfilet', amount: '600 g', estimatedPrice: 89, category: 'Kjøtt' },
      { item: 'Pitabrød', search: 'pitabrød', amount: '4 stk', estimatedPrice: 25, category: 'Tørrvarer' },
      { item: 'Gresk yoghurt', search: 'gresk yoghurt', amount: '2 dl', estimatedPrice: 22, category: 'Meieri' },
      { item: 'Agurk', search: 'agurk', amount: '1 stk', estimatedPrice: 15, category: 'Frukt/grønt' },
      { item: 'Sitron', search: 'sitron', amount: '2 stk', estimatedPrice: 14, category: 'Frukt/grønt' },
    ],
  },

  {
    id: 'kylling-sitron-hvitlok',
    name: 'Kyllinglår med sitron og hvitløk',
    type: 'meat',
    highProtein: true,
    allergens: ['gluten'],
    tags: ['kylling', 'sitron', 'hvitløk', 'ovn', 'enkel'],
    prepTime: 50,
    difficulty: 'enkel',
    leftoverFriendly: true,
    recipe: {
      servings: 4,
      steps: [
        'Sett ovnen på 200°C. Legg kyllinglår (8 stk) i en ildfast form.',
        'Press saften av 2 sitroner over kyllingen. Knus 6 hvitløkfedd og fordel rundt.',
        'Dryss over tørket oregano, salt, pepper og en god dose olivenolje.',
        'Stek i 45 minutter til skinnet er sprøtt og kyllingen er gjennomstekt (kjernetemperatur 75°C).',
        'Server med stekesjy, baguette og grønn salat.',
      ],
    },
    shoppingList: [
      { item: 'Kyllinglår', search: 'kyllinglår', amount: '8 stk', estimatedPrice: 89, category: 'Kjøtt' },
      { item: 'Sitron', search: 'sitron', amount: '2 stk', estimatedPrice: 14, category: 'Frukt/grønt' },
      { item: 'Hvitløk', search: 'hvitløk', amount: '1 hode', estimatedPrice: 10, category: 'Frukt/grønt' },
      { item: 'Baguette', search: 'baguette', amount: '1 stk', estimatedPrice: 18, category: 'Tørrvarer' },
    ],
  },

  {
    id: 'biff-bearnaise',
    name: 'Indrefilet av okse med béarnaisesaus',
    type: 'meat',
    highProtein: true,
    allergens: ['laktose', 'egg'],
    tags: ['biff', 'indrefilet', 'bearnaise', 'helg', 'restaurant'],
    prepTime: 45,
    difficulty: 'avansert',
    leftoverFriendly: false,
    recipe: {
      servings: 4,
      steps: [
        'Ta kjøttet ut av kjøleskapet 30 minutter før steking. Tørk med papir, krydre med salt og pepper.',
        'Varm en jernpanne på høyeste varme til den begynner å ryke. Stek indrefileten (ca. 700 g) 2 minutter per side, la hvile 5 minutter.',
        'Lag béarnaise: reduser hvitvin og estragoneddik (50/50) med sjalottløk til 3 ss. Pisk inn 3 eggeplommer over vannbad. Tilsett smeltet smør (200 g) dråpe for dråpe under konstant visping. Smak til med estragon, salt og pepper.',
        'Kok pommes frites eller server med ovnsbakte poteter.',
        'Skjær kjøttet på tvers av fibrene og server med béarnaise.',
      ],
    },
    shoppingList: [
      { item: 'Indrefilet av okse', search: 'indrefilet okse', amount: '700 g', estimatedPrice: 250, category: 'Kjøtt' },
      { item: 'Smør', search: 'smør', amount: '200 g', estimatedPrice: 30, category: 'Meieri' },
      { item: 'Egg', search: 'egg', amount: '3 stk', estimatedPrice: 15, category: 'Meieri' },
      { item: 'Hvitvin', search: 'hvitvin', amount: '1 dl', estimatedPrice: 25, category: 'Diverse' },
      { item: 'Estragon (tørket)', search: 'estragon krydder', amount: '1 ts', estimatedPrice: 20, category: 'Tørrvarer' },
      { item: 'Pommes frites (fryst)', search: 'pommes frites', amount: '600 g', estimatedPrice: 35, category: 'Frys' },
    ],
  },

  {
    id: 'kylling-pesto-pasta',
    name: 'Kylling med pesto og soltørkede tomater',
    type: 'meat',
    highProtein: true,
    allergens: ['gluten', 'nøtter', 'laktose'],
    tags: ['kylling', 'pesto', 'pasta', 'soltørkede tomater', 'italiensk'],
    prepTime: 25,
    difficulty: 'enkel',
    leftoverFriendly: true,
    recipe: {
      servings: 4,
      steps: [
        'Kok penne (400 g) al dente.',
        'Skjær kyllingfilet (600 g) i biter og stek i olivenolje med salt og pepper, 6–8 minutter.',
        'Tilsett soltørkede tomater (100 g, skivet), 4 ss grønn pesto og 1 dl fløte. La koke 2 minutter.',
        'Bland kyllingblandingen med den avsilte pastaen. Riv over parmesan.',
        'Server straks med frisk basilikum.',
      ],
    },
    shoppingList: [
      { item: 'Kyllingfilet', search: 'kyllingfilet', amount: '600 g', estimatedPrice: 99, category: 'Kjøtt' },
      { item: 'Penne', search: 'penne pasta', amount: '400 g', estimatedPrice: 22, category: 'Tørrvarer' },
      { item: 'Soltørkede tomater', search: 'soltørkede tomater', amount: '100 g', estimatedPrice: 30, category: 'Tørrvarer' },
      { item: 'Grønn pesto', search: 'pesto grønn', amount: '4 ss', estimatedPrice: 20, category: 'Tørrvarer' },
      { item: 'Matfløte', search: 'matfløte', amount: '1 dl', estimatedPrice: 20, category: 'Meieri' },
      { item: 'Parmesan', search: 'parmesan', amount: '40 g', estimatedPrice: 28, category: 'Meieri' },
    ],
  },

  {
    id: 'kjottkaker-brun-saus',
    name: 'Norske kjøttkaker i brun saus',
    type: 'meat',
    highProtein: true,
    allergens: ['gluten', 'egg', 'laktose'],
    tags: ['kjøttkaker', 'brun saus', 'norsk', 'tradisjonell', 'helg'],
    prepTime: 45,
    difficulty: 'middels',
    leftoverFriendly: true,
    recipe: {
      servings: 4,
      steps: [
        'Bland 600 g kjøttdeig med 1 egg, 3 ss havregryn, salt, pepper og muskat til en jevn masse. Form til ca. 12 kaker.',
        'Brun kjøttkakene i smør, 3 minutter per side. Ta ut.',
        'Lag brun saus: smelt 2 ss smør, rør inn 2 ss mel. Tilsett 5 dl oksekraft gradvis under omrøring. Smak til med pepper og timian.',
        'Legg kjøttkakene i sausen og la koke forsiktig 10 minutter.',
        'Server med potetmos, surkål og tyttebær.',
      ],
    },
    shoppingList: [
      { item: 'Kjøttdeig (blandet)', search: 'kjøttdeig blandet', amount: '600 g', estimatedPrice: 75, category: 'Kjøtt' },
      { item: 'Egg', search: 'egg', amount: '1 stk', estimatedPrice: 5, category: 'Meieri' },
      { item: 'Havregryn', search: 'havregryn', amount: '3 ss', estimatedPrice: 10, category: 'Tørrvarer' },
      { item: 'Oksekraft', search: 'oksekraft fond', amount: '5 dl', estimatedPrice: 30, category: 'Tørrvarer' },
      { item: 'Poteter', search: 'poteter', amount: '800 g', estimatedPrice: 25, category: 'Frukt/grønt' },
      { item: 'Surkål', search: 'surkål', amount: '400 g', estimatedPrice: 25, category: 'Tørrvarer' },
      { item: 'Tyttebærsyltetøy', search: 'tyttebærsyltetøy', amount: '1 glass', estimatedPrice: 35, category: 'Tørrvarer' },
    ],
  },

  {
    id: 'indisk-lammecurry',
    name: 'Indisk lammecurry (Rogan Josh)',
    type: 'meat',
    highProtein: true,
    allergens: ['laktose'],
    tags: ['lam', 'curry', 'indisk', 'rogan josh', 'krydder'],
    prepTime: 90,
    difficulty: 'avansert',
    leftoverFriendly: true,
    recipe: {
      servings: 4,
      steps: [
        'Brun lammekjøtt i biter (800 g) i en stor gryte med olje. Ta ut.',
        'Fres finhakket løk (2 stk) til gyllen. Tilsett 4 hvitløkfedd, 2 cm ingefær og krydder: 2 ts garam masala, 1 ts koriander, 1 ts spisskummen.',
        'Tilsett 2 bokser hakkede tomater og kjøttet. Hell i 2 dl vann.',
        'La koke på lav varme med lokk i 60–75 minutter til kjøttet er mørt.',
        'Rør inn 2 dl yoghurt naturell rett før servering. Server med basmatiris og naan.',
      ],
    },
    shoppingList: [
      { item: 'Lam grytekjøtt', search: 'lam grytekjøtt', amount: '800 g', estimatedPrice: 130, category: 'Kjøtt' },
      { item: 'Hakkede tomater (boks)', search: 'hakkede tomater hermetisk', amount: '2 bokser', estimatedPrice: 30, category: 'Tørrvarer' },
      { item: 'Yoghurt naturell', search: 'yoghurt naturell', amount: '2 dl', estimatedPrice: 20, category: 'Meieri' },
      { item: 'Basmatiris', search: 'basmatiris', amount: '300 g', estimatedPrice: 25, category: 'Tørrvarer' },
      { item: 'Naan', search: 'naanbrød', amount: '4 stk', estimatedPrice: 30, category: 'Tørrvarer' },
      { item: 'Garam masala', search: 'garam masala', amount: '2 ts', estimatedPrice: 20, category: 'Tørrvarer' },
    ],
  },

  {
    id: 'burger-hjemmelaget',
    name: 'Hjemmelagde burgere med karamellisert løk',
    type: 'meat',
    highProtein: true,
    allergens: ['gluten', 'egg', 'laktose', 'sennep'],
    tags: ['burger', 'kjøttdeig', 'løk', 'helg', 'grilling'],
    prepTime: 35,
    difficulty: 'enkel',
    leftoverFriendly: false,
    recipe: {
      servings: 4,
      steps: [
        'Karamelliser 3 løk (skivet) i smør på lav varme i 20 minutter til de er gyldne og søte.',
        'Form 4 store burgere av kjøttdeig (600 g). Krydre med salt og pepper. Stek på høy varme, 3–4 minutter per side.',
        'Legg cheddarost på burgerne de siste minuttet og la smelte.',
        'Rist burgerbrødene. Bygg burger: bun, sennep/ketchup, salat, tomat, burger, karamellisert løk.',
        'Server med pommes frites.',
      ],
    },
    shoppingList: [
      { item: 'Kjøttdeig (storfe)', search: 'kjøttdeig storfe', amount: '600 g', estimatedPrice: 79, category: 'Kjøtt' },
      { item: 'Burgerbrød', search: 'hamburgerbrød', amount: '4 stk', estimatedPrice: 25, category: 'Tørrvarer' },
      { item: 'Cheddar (skiver)', search: 'cheddar skivet', amount: '4 skiver', estimatedPrice: 20, category: 'Meieri' },
      { item: 'Løk', search: 'løk gul', amount: '3 stk', estimatedPrice: 15, category: 'Frukt/grønt' },
      { item: 'Salat', search: 'isbergsalat', amount: '½ hode', estimatedPrice: 15, category: 'Frukt/grønt' },
      { item: 'Pommes frites (fryst)', search: 'pommes frites', amount: '600 g', estimatedPrice: 35, category: 'Frys' },
    ],
  },

  {
    id: 'svinefilet-soppsaus',
    name: 'Svinefilet med soppsaus og poteter',
    type: 'meat',
    highProtein: true,
    allergens: ['laktose', 'gluten'],
    tags: ['svinefilet', 'sopp', 'saus', 'poteter'],
    prepTime: 40,
    difficulty: 'middels',
    leftoverFriendly: true,
    recipe: {
      servings: 4,
      steps: [
        'Brun svinefilet (600 g) på alle sider i smør. Overfør til ovn på 180°C i 15–18 minutter (kjernetemperatur 68°C). La hvile.',
        'Fres skivet sjampinjong (300 g) og 1 sjalottløk i samme panne til soppen er gyllen.',
        'Tilsett 2 dl fløte og 1 dl kjøttkraft. La koke ned til en tykk saus, ca. 5 minutter.',
        'Skjær svinefileten i skiver. Server med soppsaus og ovnsbakte poteter.',
      ],
    },
    shoppingList: [
      { item: 'Svinefilet', search: 'svinefilet', amount: '600 g', estimatedPrice: 99, category: 'Kjøtt' },
      { item: 'Sjampinjong', search: 'sjampinjong fersk', amount: '300 g', estimatedPrice: 30, category: 'Frukt/grønt' },
      { item: 'Matfløte', search: 'matfløte', amount: '2 dl', estimatedPrice: 30, category: 'Meieri' },
      { item: 'Kjøttkraft', search: 'kjøttkraft fond', amount: '1 dl', estimatedPrice: 20, category: 'Tørrvarer' },
      { item: 'Poteter', search: 'poteter', amount: '800 g', estimatedPrice: 25, category: 'Frukt/grønt' },
    ],
  },

  {
    id: 'kyllingcaesar-salat',
    name: 'Kylling Caesar-salat',
    type: 'meat',
    highProtein: true,
    allergens: ['gluten', 'egg', 'fisk', 'laktose'],
    tags: ['kylling', 'salat', 'caesar', 'romasalat', 'lett'],
    prepTime: 25,
    difficulty: 'enkel',
    leftoverFriendly: true,
    recipe: {
      servings: 4,
      steps: [
        'Krydre kyllingfileter (600 g) med salt, pepper og paprika. Stek 5–6 minutter per side. La hvile og skjær i skiver.',
        'Lag croutoner: kutt daggammelt brød i terninger, stek i olivenolje med hvitløk til sprø og gylne.',
        'Lag dressing: bland 3 ss majones, 1 ss Worcestershire, 1 ss sitronsaft, 1 fedd revet hvitløk og revet parmesan.',
        'Riv romasalat (2 hoder) grovt. Bland med dressing, croutoner og kylling.',
        'Topp med revet parmesan og sort pepper.',
      ],
    },
    shoppingList: [
      { item: 'Kyllingfilet', search: 'kyllingfilet', amount: '600 g', estimatedPrice: 99, category: 'Kjøtt' },
      { item: 'Romasalat', search: 'romasalat', amount: '2 hoder', estimatedPrice: 40, category: 'Frukt/grønt' },
      { item: 'Parmesan', search: 'parmesan', amount: '50 g', estimatedPrice: 32, category: 'Meieri' },
      { item: 'Majones', search: 'majones', amount: '3 ss', estimatedPrice: 15, category: 'Tørrvarer' },
      { item: 'Brød (daggammelt)', search: 'brød', amount: '2 skiver', estimatedPrice: 5, category: 'Tørrvarer' },
    ],
  },

  {
    id: 'kylling-marokkansk',
    name: 'Marokkansk kyllingtagine med couscous',
    type: 'meat',
    highProtein: true,
    allergens: ['gluten', 'nøtter'],
    tags: ['kylling', 'tagine', 'marokkansk', 'couscous', 'eksotisk'],
    prepTime: 60,
    difficulty: 'middels',
    leftoverFriendly: true,
    recipe: {
      servings: 4,
      steps: [
        'Brun kyllinglår (8 stk) i olje. Ta ut.',
        'Fres løk til myk. Tilsett 2 ts ras el hanout, 1 ts ingefær, ½ ts kanel og 2 fedd hvitløk, stek 1 minutt.',
        'Tilsett 2 dl kyllingkraft, 1 boks hakkede tomater, 100 g grønne oliven og kyllingen. La koke under lokk 35–40 minutter.',
        'Tilsett 50 g tørkede aprikoser de siste 10 minuttene.',
        'Kok couscous (300 g) etter pakningsanvisning. Server taginen over couscous med ristede mandelflak.',
      ],
    },
    shoppingList: [
      { item: 'Kyllinglår', search: 'kyllinglår', amount: '8 stk', estimatedPrice: 89, category: 'Kjøtt' },
      { item: 'Couscous', search: 'couscous', amount: '300 g', estimatedPrice: 25, category: 'Tørrvarer' },
      { item: 'Ras el hanout', search: 'ras el hanout krydder', amount: '2 ts', estimatedPrice: 20, category: 'Tørrvarer' },
      { item: 'Tørkede aprikoser', search: 'aprikoser tørkede', amount: '50 g', estimatedPrice: 20, category: 'Tørrvarer' },
      { item: 'Grønne oliven', search: 'oliven grønne', amount: '100 g', estimatedPrice: 25, category: 'Tørrvarer' },
      { item: 'Mandelflak', search: 'mandelflak', amount: '30 g', estimatedPrice: 18, category: 'Tørrvarer' },
    ],
  },

  {
    id: 'entrecote-chimichurri',
    name: 'Entrecôte med chimichurri og ovnsbakte poteter',
    type: 'meat',
    highProtein: true,
    allergens: [],
    tags: ['entrecôte', 'biff', 'chimichurri', 'argentinsk', 'grilling'],
    prepTime: 35,
    difficulty: 'middels',
    leftoverFriendly: false,
    recipe: {
      servings: 4,
      steps: [
        'Kutt poteter (600 g) i båter. Bland med olivenolje, salt, pepper og paprika. Stek i ovn på 220°C i 25 minutter.',
        'Lag chimichurri: finhakk en stor bunt persille og 4 hvitløkfedd. Bland med 4 ss olivenolje, 2 ss rødvinseddik, salt, pepper og chiliflak.',
        'La entrecôtene (4 stk, ca. 200 g/stk) komme til romtemperatur. Krydre godt med salt og pepper.',
        'Stek på meget varm grillpanne, 3 minutter per side for medium rare. La hvile 5 minutter.',
        'Server biffen med chimichurri og ovnsbakte poteter.',
      ],
    },
    shoppingList: [
      { item: 'Entrecôte (4 stk)', search: 'entrecote biff', amount: '800 g', estimatedPrice: 200, category: 'Kjøtt' },
      { item: 'Poteter', search: 'poteter', amount: '600 g', estimatedPrice: 22, category: 'Frukt/grønt' },
      { item: 'Persille', search: 'persille fersk', amount: '1 bunt', estimatedPrice: 18, category: 'Frukt/grønt' },
      { item: 'Rødvinseddik', search: 'rødvinseddik', amount: '2 ss', estimatedPrice: 15, category: 'Tørrvarer' },
    ],
  },

  {
    id: 'kylling-teriyaki-wraps',
    name: 'Teriyaki-kylling wraps',
    type: 'meat',
    highProtein: true,
    allergens: ['gluten', 'soya', 'sesam'],
    tags: ['kylling', 'teriyaki', 'wrap', 'asiatisk', 'hverdagsmat'],
    prepTime: 20,
    difficulty: 'enkel',
    leftoverFriendly: true,
    recipe: {
      servings: 4,
      steps: [
        'Bland 4 ss soyasaus, 2 ss honning og 1 ss sesamolje til teriyaki-marinade.',
        'Stek kyllingfilet (600 g) i strimler på høy varme i 5–6 minutter. Hell over marinaden og la koke inn 2 minutter.',
        'Riv hodekål fint, riv gulrøtter (2 stk) på grovt rivjern.',
        'Varm tortillaene i tørr panne. Fyll med kål, gulrot, kylling og sesamfrø.',
        'Server med sweet chili sauce.',
      ],
    },
    shoppingList: [
      { item: 'Kyllingfilet', search: 'kyllingfilet', amount: '600 g', estimatedPrice: 99, category: 'Kjøtt' },
      { item: 'Tortilla', search: 'tortilla hvete', amount: '8 stk', estimatedPrice: 25, category: 'Tørrvarer' },
      { item: 'Hodekål', search: 'hodekål', amount: '¼ hode', estimatedPrice: 10, category: 'Frukt/grønt' },
      { item: 'Gulrøtter', search: 'gulrøtter', amount: '2 stk', estimatedPrice: 10, category: 'Frukt/grønt' },
      { item: 'Soyasaus', search: 'soyasaus', amount: '4 ss', estimatedPrice: 20, category: 'Tørrvarer' },
      { item: 'Honning', search: 'honning', amount: '2 ss', estimatedPrice: 15, category: 'Tørrvarer' },
    ],
  },

  {
    id: 'pho-kylling',
    name: 'Vietnamesisk pho med kylling',
    type: 'meat',
    highProtein: true,
    allergens: ['gluten', 'soya'],
    tags: ['pho', 'kylling', 'vietnamesisk', 'suppe', 'nudler'],
    prepTime: 50,
    difficulty: 'middels',
    leftoverFriendly: true,
    recipe: {
      servings: 4,
      steps: [
        'Tørrrist 2 stjerneanis, 3 nellik og 1 kanelstang i en tørr gryte i 2 minutter.',
        'Tilsett 1,5 l kyllingkraft, 2 cm ingefær og kok i 30 minutter. Sil av.',
        'Kok risnudler (200 g) etter pakningsanvisning.',
        'Skjær kokt kyllingbryst (500 g) tynt. Fordel nudler og kylling i boller, hell over den varme kraften.',
        'Server med bønnespirer, lime, basilikum, chili og hoisinsaus på bordet.',
      ],
    },
    shoppingList: [
      { item: 'Kyllingbryst', search: 'kyllingbryst', amount: '500 g', estimatedPrice: 89, category: 'Kjøtt' },
      { item: 'Risnudler', search: 'risnudler', amount: '200 g', estimatedPrice: 25, category: 'Tørrvarer' },
      { item: 'Kyllingkraft', search: 'kyllingkraft fond', amount: '1,5 liter', estimatedPrice: 40, category: 'Tørrvarer' },
      { item: 'Bønnespirer', search: 'bønnespirer', amount: '100 g', estimatedPrice: 20, category: 'Frukt/grønt' },
      { item: 'Lime', search: 'lime', amount: '2 stk', estimatedPrice: 14, category: 'Frukt/grønt' },
      { item: 'Hoisinsaus', search: 'hoisinsaus', amount: '3 ss', estimatedPrice: 20, category: 'Tørrvarer' },
    ],
  },

  {
    id: 'svinekjaker-rodvin',
    name: 'Svinekjaker i rødvin med rotmos',
    type: 'meat',
    highProtein: true,
    allergens: ['laktose'],
    tags: ['svinekjaker', 'rødvin', 'rotmos', 'helg', 'bistro'],
    prepTime: 150,
    difficulty: 'avansert',
    leftoverFriendly: true,
    recipe: {
      servings: 4,
      steps: [
        'Brun svinekjaker (800 g) på alle sider i en gryte. Ta ut.',
        'Fres grovhakket løk, gulrot og selleri i gryten. Tilsett 2 ss tomatpuré og stek 2 minutter.',
        'Hell i 3 dl rødvin og 3 dl kjøttkraft. Tilsett timian, laurbærblad og kjøttet.',
        'La putre under lokk på lav varme i 2–2,5 timer til kjøttet er svært mørt.',
        'Kok kålrot og poteter til rotmos med smør og fløte. Sil sausen og smak til. Server.',
      ],
    },
    shoppingList: [
      { item: 'Svinekjaker', search: 'svinekjaker', amount: '800 g', estimatedPrice: 110, category: 'Kjøtt' },
      { item: 'Rødvin', search: 'rødvin matlaging', amount: '3 dl', estimatedPrice: 40, category: 'Diverse' },
      { item: 'Kjøttkraft', search: 'kjøttkraft fond', amount: '3 dl', estimatedPrice: 25, category: 'Tørrvarer' },
      { item: 'Kålrot', search: 'kålrot', amount: '300 g', estimatedPrice: 12, category: 'Frukt/grønt' },
      { item: 'Poteter', search: 'poteter', amount: '500 g', estimatedPrice: 18, category: 'Frukt/grønt' },
      { item: 'Matfløte', search: 'matfløte', amount: '1 dl', estimatedPrice: 20, category: 'Meieri' },
    ],
  },

  {
    id: 'kylling-gyros',
    name: 'Kyllinggyros med tzatziki og pita',
    type: 'meat',
    highProtein: true,
    allergens: ['gluten', 'laktose'],
    tags: ['kylling', 'gyros', 'gresk', 'pita', 'tzatziki'],
    prepTime: 30,
    difficulty: 'enkel',
    leftoverFriendly: true,
    recipe: {
      servings: 4,
      steps: [
        'Mariner kyllingfilet (600 g) i 2 ts oregano, 1 ts paprika, 1 ts hvitløkspulver, sitronsaft og olivenolje i 15 minutter.',
        'Stek kyllingen i panne 5–6 minutter per side. Skjær i strimler.',
        'Lag tzatziki: riv agurk (½ stk) og klem ut overflødig vann. Bland med gresk yoghurt (2 dl), hvitløk, dill, sitronsaft og salt.',
        'Varm pitabrød. Fyll med kylling, tzatziki, tomat og rødløk.',
      ],
    },
    shoppingList: [
      { item: 'Kyllingfilet', search: 'kyllingfilet', amount: '600 g', estimatedPrice: 99, category: 'Kjøtt' },
      { item: 'Pitabrød', search: 'pitabrød', amount: '8 stk', estimatedPrice: 25, category: 'Tørrvarer' },
      { item: 'Gresk yoghurt', search: 'gresk yoghurt', amount: '2 dl', estimatedPrice: 25, category: 'Meieri' },
      { item: 'Agurk', search: 'agurk', amount: '½ stk', estimatedPrice: 10, category: 'Frukt/grønt' },
      { item: 'Tomat', search: 'tomat', amount: '2 stk', estimatedPrice: 15, category: 'Frukt/grønt' },
      { item: 'Rødløk', search: 'rødløk', amount: '1 stk', estimatedPrice: 8, category: 'Frukt/grønt' },
    ],
  },

  {
    id: 'svinerib-asiatisk',
    name: 'Asiatiske svinerater med honning og ingefær',
    type: 'meat',
    highProtein: true,
    allergens: ['gluten', 'soya', 'sesam'],
    tags: ['svineribbe', 'honning', 'ingefær', 'asiatisk', 'helg'],
    prepTime: 120,
    difficulty: 'middels',
    leftoverFriendly: true,
    recipe: {
      servings: 4,
      steps: [
        'Lag marinade: bland 4 ss soyasaus, 3 ss honning, 2 ss hoisinsaus, 2 cm revet ingefær, 3 hvitløkfedd og 1 ss sesamolje.',
        'Mariner svinerater (1 kg) i minimum 1 time, gjerne over natten.',
        'Sett ovn på 160°C. Pakk ribbeina i folie og stek i 90 minutter.',
        'Ta av folien, øk til 220°C og pensle med ekstra marinade. Stek 10–15 minutter til karamellisert.',
        'Server med jasminris, dampet pak choi og sesamfrø.',
      ],
    },
    shoppingList: [
      { item: 'Svinerater/spareribs', search: 'svinerater spareribs', amount: '1 kg', estimatedPrice: 110, category: 'Kjøtt' },
      { item: 'Soyasaus', search: 'soyasaus', amount: '4 ss', estimatedPrice: 15, category: 'Tørrvarer' },
      { item: 'Honning', search: 'honning', amount: '3 ss', estimatedPrice: 20, category: 'Tørrvarer' },
      { item: 'Hoisinsaus', search: 'hoisinsaus', amount: '2 ss', estimatedPrice: 20, category: 'Tørrvarer' },
      { item: 'Jasminris', search: 'jasminris', amount: '300 g', estimatedPrice: 20, category: 'Tørrvarer' },
      { item: 'Pak choi', search: 'pak choi', amount: '2 stk', estimatedPrice: 25, category: 'Frukt/grønt' },
    ],
  },

  {
    id: 'okse-stroganoff',
    name: 'Oksekjøtt Stroganoff med nudler',
    type: 'meat',
    highProtein: true,
    allergens: ['gluten', 'laktose'],
    tags: ['okse', 'stroganoff', 'nudler', 'russisk', 'kremet'],
    prepTime: 35,
    difficulty: 'enkel',
    leftoverFriendly: true,
    recipe: {
      servings: 4,
      steps: [
        'Skjær oksemørbrad (500 g) i strimler. Brun raskt i smør på høy varme. Ta ut.',
        'Fres skivet løk og sjampinjong (200 g) i samme panne til gyldne.',
        'Tilsett 1 ss tomatpuré, 2 ts Worcestershire og 2 dl oksekraft. La koke 3 minutter.',
        'Rør inn 2 dl rømme og kjøttet. La trekke på lav varme 5 minutter (ikke koke).',
        'Server over eggnudler med finhakket persille.',
      ],
    },
    shoppingList: [
      { item: 'Oksemørbrad el. entrecôte i strimler', search: 'oksekjøtt mørbrad', amount: '500 g', estimatedPrice: 130, category: 'Kjøtt' },
      { item: 'Sjampinjong', search: 'sjampinjong fersk', amount: '200 g', estimatedPrice: 25, category: 'Frukt/grønt' },
      { item: 'Rømme', search: 'rømme', amount: '2 dl', estimatedPrice: 25, category: 'Meieri' },
      { item: 'Eggnudler', search: 'eggnudler', amount: '400 g', estimatedPrice: 25, category: 'Tørrvarer' },
      { item: 'Oksekraft', search: 'oksekraft fond', amount: '2 dl', estimatedPrice: 20, category: 'Tørrvarer' },
    ],
  },

];
