// meals-fish.js — fiskeoppskrifter
// For å legge til en ny oppskrift: kopier én blokk og endre feltene.
// highProtein: true = > ~25 g protein per porsjon

export const FISH_MEALS = [

  {
    id: 'laksepasta',
    name: 'Laksepasta med spinat',
    type: 'fish',
    highProtein: true,
    allergens: ['fisk', 'gluten', 'laktose'],
    tags: ['laks', 'pasta', 'fisk', 'spinat'],
    prepTime: 25,
    difficulty: 'enkel',
    leftoverFriendly: true,
    vegetarianAlternative: 'Pasta med spinat og ricotta',
    recipe: {
      servings: 4,
      steps: [
        'Kok opp rikelig med lettsaltet vann i en stor kjele. Kok fullkornspasta (400 g) etter anvisning på pakken, men ta den av 1 minutt før anbefalt tid – den skal være al dente (ha litt tyggemotstand). Spar 1 dl pastavann før du heller av.',
        'Mens pastaen koker: tørk laksefileten (400 g) med kjøkkenpapir og skjær i porsjonsstykker. Krydre godt med salt og pepper på begge sider.',
        'Varm en stor stekepanne på middels høy varme og smelt en god klatt smør (ca. 1 ss) til det slutter å bruse. Legg i laksen med skinnsiden ned og stek 3 minutter uten å røre. Snu forsiktig og stek 2–3 minutter til. Laksen er ferdig når den flaker seg lett med en gaffel. Ta den ut og sett til side.',
        'Skru varmen ned til middels. Finhakk 2 hvitløkfedd og stek dem i pannen i 30 sekunder til de er gyldne, men ikke brune. Tilsett fersk spinat (150 g) og rør til den faller sammen, ca. 2 minutter.',
        'Tilsett den avsilte pastaen i pannen og rør godt. Hell i litt av det sparte pastavannet og rør videre – stivelsen i vannet binder sausen. Del laksen i store flak og vend den forsiktig inn.',
        'Server umiddelbart i dype tallerkener. Riv parmesan (50 g) over og press over litt sitronsaft.',
      ],
    },
    shoppingList: [
      { item: 'Laksefilet', search: 'laksefilet', amount: '400 g', estimatedPrice: 89, category: 'Fisk' },
      { item: 'Pasta (fullkorn)', search: 'fullkornspasta', amount: '400 g', estimatedPrice: 28, category: 'Tørrvarer' },
      { item: 'Fersk spinat', search: 'spinat fersk', amount: '150 g', estimatedPrice: 35, category: 'Frukt/grønt' },
      { item: 'Hvitløk', search: 'hvitløk', amount: '2 fedd', estimatedPrice: 5, category: 'Frukt/grønt' },
      { item: 'Parmesan', search: 'parmesan', amount: '50 g', estimatedPrice: 32, category: 'Meieri' },
    ],
  },

  {
    id: 'torsk-rotgronnsaker',
    name: 'Torsk med ovnsbakte rotgrønnsaker',
    type: 'fish',
    highProtein: true,
    allergens: ['fisk'],
    tags: ['torsk', 'fisk', 'ovn', 'rotgrønnsaker'],
    prepTime: 35,
    difficulty: 'enkel',
    leftoverFriendly: false,
    vegetarianAlternative: 'Ovnsbakt blomkål med rotgrønnsaker',
    recipe: {
      servings: 4,
      steps: [
        'Forvarm ovnen til 200 °C over-/undervarme. Kle en langpanne med bakepapir.',
        'Skrell og skjær gulrot (3 stk), pastinakk (2 stk) og potet (400 g) i jevnstore biter, ca. 3×3 cm, slik at alt stekes ferdig samtidig.',
        'Legg grønnsakene i langpannen og hell over 3 ss olivenolje. Krydre godt med salt, pepper og gjerne litt timian eller rosmarin. Vend godt slik at alle bitene er dekket med olje. Stek midt i ovnen i 20 minutter til de begynner å bli møre og få litt farge.',
        'Tørk torskefilet (500 g) med kjøkkenpapir og skjær i 4 porsjoner. Krydre med salt, pepper og litt sitronsaft. Legg filetene oppå de halvstekte grønnsakene og dryss over litt olivenolje.',
        'Stek videre i 10–12 minutter til torsken er gjennomkokt. Torsken er ferdig når den er hvit og ugjennomsiktig hele veien gjennom, og du kan løfte av lag med en gaffel. Unngå å oversteke – torsk tørker raskt ut.',
        'Server direkte fra langpannen med hakket fersk persille og sitronbåter til å klemme over.',
      ],
    },
    shoppingList: [
      { item: 'Torskefilet', search: 'torskefilet', amount: '500 g', estimatedPrice: 79, category: 'Fisk' },
      { item: 'Gulrot', search: 'gulrot', amount: '3 stk', estimatedPrice: 12, category: 'Frukt/grønt' },
      { item: 'Pastinakk', search: 'pastinakk', amount: '2 stk', estimatedPrice: 18, category: 'Frukt/grønt' },
      { item: 'Potet', search: 'potet', amount: '400 g', estimatedPrice: 15, category: 'Frukt/grønt' },
      { item: 'Sitron', search: 'sitron', amount: '1 stk', estimatedPrice: 8, category: 'Frukt/grønt' },
    ],
  },

  {
    id: 'ørret-dill',
    name: 'Ørretfilet med dillpoteter og erter',
    type: 'fish',
    highProtein: true,
    allergens: ['fisk', 'laktose'],
    tags: ['ørret', 'fisk', 'potet', 'dill'],
    prepTime: 30,
    difficulty: 'enkel',
    leftoverFriendly: false,
    vegetarianAlternative: 'Stekt tofu med dillpoteter og erter',
    recipe: {
      servings: 4,
      steps: [
        'Skrubb potetene (600 g) og del dem i to om de er store. Legg i en kjele, dekk med kaldt vann og tilsett en god klype salt. Kok opp og la koke 15–18 minutter til en kniv glir lett inn. Hell av vannet og sett til side med lokk.',
        'Tørk ørretfiletene (500 g) grundig med kjøkkenpapir – er de våte, svir de ikke ordentlig. Krydre begge sider med salt og pepper.',
        'Smelt en generøs klatt smør (ca. 1½ ss) i en stekepanne på middels høy varme. Når smøret slutter å bruse, legg i ørretfiletene med skinnsiden ned. Stek 3–4 minutter uten å røre til skinnet er sprøtt og gyldig. Snu forsiktig med en stekespade og stek 2–3 minutter til på den andre siden. Fisken er ferdig når den er ugjennomsiktig i midten.',
        'Kok frosne erter (200 g) i lettsaltet vann i 2 minutter, eller følg anvisningen på pakken. Hell av vannet.',
        'Vend de varme potetene med en god klatt smør (ca. 1 ss), grovhakket fersk dill (halve bunten) og litt sitronsaft. Smak til med salt og pepper.',
        'Server ørretfiletene med dillpotetene og ertene. Legg resten av dillen over fisken og press litt sitron over alt.',
      ],
    },
    shoppingList: [
      { item: 'Ørretfilet', search: 'ørretfilet', amount: '500 g', estimatedPrice: 89, category: 'Fisk' },
      { item: 'Potet', search: 'potet', amount: '600 g', estimatedPrice: 18, category: 'Frukt/grønt' },
      { item: 'Frosne erter', search: 'frosne erter', amount: '200 g', estimatedPrice: 22, category: 'Frys' },
      { item: 'Fersk dill', search: 'dill fersk', amount: '1 bunt', estimatedPrice: 15, category: 'Frukt/grønt' },
      { item: 'Smør', search: 'smør', amount: '50 g', estimatedPrice: 12, category: 'Meieri' },
    ],
  },

  {
    id: 'fiskesuppe',
    name: 'Kremet fiskesuppe med rotgrønnsaker',
    type: 'fish',
    highProtein: false,
    allergens: ['fisk', 'laktose', 'selleri'],
    tags: ['fiskesuppe', 'fisk', 'suppe', 'torsk', 'laks'],
    prepTime: 30,
    difficulty: 'enkel',
    leftoverFriendly: true,
    vegetarianAlternative: 'Kremet grønnsakssuppe med kokosmelk',
    recipe: {
      servings: 4,
      steps: [
        'Finhakk løk (1 stk) og selleri (2 stilker). Skrell og terning gulrot (2 stk) og potet (300 g) i ca. 2 cm biter.',
        'Smelt smør (1 ss) i en stor kjele på middels varme. Stek løk og selleri under omrøring i 4–5 minutter til de er myke og gjennomsiktige, uten å ta farge.',
        'Tilsett gulrot og potet og rør rundt i 1 minutt. Hell over fiskekraft (eller 1 l vann + 1 fiskebuljongtablette) og matfløte (2 dl). Rør godt. Kok opp, skru ned varmen og la småkoke med lokk i 10 minutter til potet og gulrot er nesten møre.',
        'Skjær laks og torsk (totalt 500 g) i store terninger, ca. 3×3 cm. Legg fisken forsiktig ned i suppen og la den trekke på svak varme – suppen skal ikke koke – i 5 minutter til fisken er hvit og gjennomkokt.',
        'Smak til med salt og hvit pepper. Tilsett gjerne litt sitronsaft for friskhet.',
        'Hakk fersk dill og dryss over ved servering. Server med godt brød.',
      ],
    },
    shoppingList: [
      { item: 'Laks (filet)', search: 'laksefilet', amount: '250 g', estimatedPrice: 55, category: 'Fisk' },
      { item: 'Torskefilet', search: 'torskefilet', amount: '250 g', estimatedPrice: 45, category: 'Fisk' },
      { item: 'Matfløte', search: 'matfløte', amount: '2 dl', estimatedPrice: 28, category: 'Meieri' },
      { item: 'Gulrot', search: 'gulrot', amount: '2 stk', estimatedPrice: 8, category: 'Frukt/grønt' },
      { item: 'Potet', search: 'potet', amount: '300 g', estimatedPrice: 12, category: 'Frukt/grønt' },
      { item: 'Selleri', search: 'selleri stilk', amount: '2 stk', estimatedPrice: 10, category: 'Frukt/grønt' },
    ],
  },

  {
    id: 'ovnslaks-quinoa',
    name: 'Ovnslaks med quinoa og brokkoli',
    type: 'fish',
    highProtein: true,
    allergens: ['fisk'],
    tags: ['laks', 'fisk', 'ovn', 'quinoa', 'brokkoli', 'sunn'],
    prepTime: 30,
    difficulty: 'enkel',
    leftoverFriendly: true,
    vegetarianAlternative: 'Ovnsbakt søtpotet med quinoa og brokkoli',
    recipe: {
      servings: 4,
      steps: [
        'Forvarm ovnen til 200 °C. Skyll quinoa (300 g) i kaldt vann i en sil til vannet renner klart – dette fjerner det bitre belegget. Ha quinoaen i en kjele med 600 ml vann og ½ ts salt. Kok opp, skru ned til svak varme og la trekke med lokk i 15 minutter til vannet er absorbert. La hvile 5 minutter med lokk, deretter løsne med en gaffel.',
        'Tørk laksefiletene (500 g) og legg dem i en ildfast form. Riv over sitronskall fra 1 sitron, finhakk 2 hvitløkfedd og fordel over fisken. Dryss salt og pepper og drypp litt olivenolje over.',
        'Sett laksen midt i ovnen og stek 13–15 minutter. Laksen er ferdig når den er ugjennomsiktig i midten men fortsatt litt saftig – stikk med en kniv i det tykkeste stedet og titt inn.',
        'Mens laksen stekes: del brokkolien (1 hode) i buketter og kok i lettsaltet vann i 4–5 minutter til den er mør men fortsatt har litt «bitt». Hell av vannet.',
        'Fordel quinoa på tallerkener, legg brokkoli ved siden av og laksen på toppen. Legg en teskje pesto på hver lakseporsjon og press litt sitronsaft over.',
      ],
    },
    shoppingList: [
      { item: 'Laksefilet', search: 'laksefilet', amount: '500 g', estimatedPrice: 99, category: 'Fisk' },
      { item: 'Quinoa', search: 'quinoa', amount: '300 g', estimatedPrice: 45, category: 'Tørrvarer' },
      { item: 'Brokkoli', search: 'brokkoli', amount: '1 hode', estimatedPrice: 25, category: 'Frukt/grønt' },
      { item: 'Pesto', search: 'pesto', amount: '2 ss', estimatedPrice: 15, category: 'Tørrvarer' },
      { item: 'Sitron', search: 'sitron', amount: '1 stk', estimatedPrice: 8, category: 'Frukt/grønt' },
    ],
  },

  {
    id: 'seibiff',
    name: 'Seibiff med sautert løk og stekte poteter',
    type: 'fish',
    highProtein: true,
    allergens: ['fisk', 'laktose'],
    tags: ['sei', 'fisk', 'biff', 'norsk', 'potet'],
    prepTime: 30,
    difficulty: 'enkel',
    leftoverFriendly: false,
    vegetarianAlternative: 'Soyabiff med sautert løk og stekte poteter',
    recipe: {
      servings: 4,
      steps: [
        'Skjær poteter (600 g) i jevne terninger, ca. 2×2 cm. Varm olje (2 ss) i en stor stekepanne på middels høy varme. Legg i potetterningene i ett lag og stek uten å røre i 5–6 minutter til de er gyldne på undersiden. Snu og stek videre 8–10 minutter til de er gjennomstekte og sprø på utsiden. Krydre med salt og pepper. Ta dem ut og hold varme.',
        'Skjær seifileten (500 g) i fire porsjoner og tørk dem godt med kjøkkenpapir. Krydre med salt og pepper på begge sider.',
        'Smelt smør (1 ss) i samme panne på middels høy varme. Stek seibiffene 3–4 minutter per side til de er gjennomkokte og har fått en gyllen stekeskorpe. Fisken er ferdig når den er ugjennomsiktig hele veien gjennom. Ta ut og hold varm.',
        'Skjær løk (3 stk) i tynne halvmåner. Bruk samme panne (skru ned til middels varme) og stek løken i 8–10 minutter under jevnlig omrøring til den er myk, søt og lett karamellisert. Tilsett gjerne friske timiankvister de siste 2 minuttene.',
        'Legg potetene på tallerkener, plasser seibifffen oppå og topp med den sauterte løken. Server umiddelbart.',
      ],
    },
    shoppingList: [
      { item: 'Seifilet', search: 'seifilet', amount: '500 g', estimatedPrice: 69, category: 'Fisk' },
      { item: 'Potet', search: 'potet', amount: '600 g', estimatedPrice: 18, category: 'Frukt/grønt' },
      { item: 'Løk', search: 'løk', amount: '3 stk', estimatedPrice: 12, category: 'Frukt/grønt' },
      { item: 'Smør', search: 'smør', amount: '50 g', estimatedPrice: 12, category: 'Meieri' },
      { item: 'Fersk timian', search: 'timian fersk', amount: '5 kvister', estimatedPrice: 12, category: 'Frukt/grønt' },
    ],
  },

  {
    id: 'asiatisk-laksesuppe',
    name: 'Asiatisk laksesuppe med nudler',
    type: 'fish',
    highProtein: false,
    allergens: ['fisk', 'gluten', 'soya'],
    tags: ['laks', 'fisk', 'asiatisk', 'suppe', 'nudler', 'ingefær'],
    prepTime: 25,
    difficulty: 'enkel',
    leftoverFriendly: false,
    vegetarianAlternative: 'Asiatisk grønnsakssuppe med tofu og nudler',
    recipe: {
      servings: 4,
      steps: [
        'Skrell og finhakk ingefær (2 cm fersk), 2 hvitløkfedd og en liten rød chili (valgfritt, fjern frø for mildere smak).',
        'Varm litt olje i en stor gryte på middels varme. Fres ingefær, hvitløk og chili i 1 minutt under omrøring til det dufter – pass på at det ikke svir.',
        'Hell over kylling- eller grønnsaksbuljong (1 l), tilsett soyasaus (3 ss) og kok opp. Smak til – suppen skal være salt og smaksrik som base.',
        'Legg risnudlene (200 g) i suppen og kok 3 minutter (eller etter anvisning på pakken). Tilsett pak choi (200 g) delt i to på langs og kok 2 minutter til til grønnsaken er myk men fortsatt litt sprø.',
        'Skjær laksefilet (400 g) i terninger, ca. 3×3 cm. Skru ned varmen slik at suppen trekker istedenfor å koke kraftig. Legg i laksen og la trekke 4–5 minutter til den er hvit og gjennomkokt.',
        'Fordel i dype boller. Press over limesaft, legg på fersk koriander og server med ekstra soyasaus og chili ved siden av.',
      ],
    },
    shoppingList: [
      { item: 'Laksefilet', search: 'laksefilet', amount: '400 g', estimatedPrice: 89, category: 'Fisk' },
      { item: 'Risnudler', search: 'risnudler', amount: '200 g', estimatedPrice: 25, category: 'Tørrvarer' },
      { item: 'Pak choi', search: 'pak choi', amount: '200 g', estimatedPrice: 20, category: 'Frukt/grønt' },
      { item: 'Soyasaus', search: 'soyasaus', amount: '3 ss', estimatedPrice: 8, category: 'Tørrvarer' },
      { item: 'Ingefær (fersk)', search: 'ingefær fersk', amount: '2 cm', estimatedPrice: 5, category: 'Frukt/grønt' },
    ],
  },

  {
    id: 'fiskegrateng',
    name: 'Fiskegrateng med makaroni',
    type: 'fish',
    highProtein: true,
    allergens: ['fisk', 'gluten', 'laktose', 'egg'],
    tags: ['fiskegrateng', 'fisk', 'grateng', 'norsk', 'makaroni'],
    prepTime: 45,
    difficulty: 'enkel',
    leftoverFriendly: true,
    vegetarianAlternative: 'Makaronigrateng med ricotta og spinat',
    recipe: {
      servings: 4,
      steps: [
        'Forvarm ovnen til 200 °C. Legg torskefilet (400 g) i en kjele, dekk med kaldt vann og tilsett salt. Kok opp og la trekke på svak varme i 8 minutter til fisken er hvit og gjennomkokt. Ta ut fisken, avkjøl litt og flak den grovt med hendene. Pass nøye på bein.',
        'Kok makaroni (300 g) i lettsaltet vann til al dente – ta den av 2 minutter før anbefalt tid. Hell av.',
        'Lag hvit saus (bechamel): smelt smør (3 ss) i en kjele på middels varme. Rør inn hvetemel (3 ss) og rør konstant i 1–2 minutter til blandingen boblier og lukter litt nøtteaktig – dette er roux. Hell i varm melk (5 dl) litt etter litt under kontinuerlig omrøring med en visp for å unngå klumper. Rør til sausen er jevn og tykk, ca. 5 minutter. Smak til med salt, pepper og et lite dryss muskatnøtt.',
        'Bland den avsilte makaronien med hvit saus, fiskeflaket og halvparten av revet ost (ca. 75 g). Vend forsiktig.',
        'Hell blandingen over i en smurt ildfast form (ca. 25×35 cm). Dryss over resten av osten og gjerne litt brødsmuler for sprø topp.',
        'Stek midt i ovnen i 20–25 minutter til overflaten er gylden og gratengen bobler langs kantene. La hvile 5 minutter før servering.',
      ],
    },
    shoppingList: [
      { item: 'Torskefilet', search: 'torskefilet', amount: '400 g', estimatedPrice: 79, category: 'Fisk' },
      { item: 'Makaroni', search: 'makaroni', amount: '300 g', estimatedPrice: 18, category: 'Tørrvarer' },
      { item: 'Melk (hel)', search: 'helmelk', amount: '5 dl', estimatedPrice: 12, category: 'Meieri' },
      { item: 'Revet ost', search: 'revet ost', amount: '150 g', estimatedPrice: 35, category: 'Meieri' },
      { item: 'Hvetemel', search: 'hvetemel', amount: '3 ss', estimatedPrice: 4, category: 'Tørrvarer' },
    ],
  },

  // ── MIDDELS KOMPLEKSE OPPSKRIFTER ─────────────────────────────────────────

  {
    id: 'bacalao',
    name: 'Bacalao med oliven, tomater og poteter',
    type: 'fish',
    highProtein: true,
    allergens: ['fisk'],
    tags: ['bacalao', 'klippfisk', 'fisk', 'middelhavet', 'spansk', 'norsk', 'tradisjonell'],
    prepTime: 60,
    difficulty: 'middels',
    leftoverFriendly: true,
    vegetarianAlternative: 'Poteter med oliven og paprika i tomatsaus',
    recipe: {
      servings: 4,
      steps: [
        'Utvann klippfisk (600 g) i minst 24 timer – bytt vann 3–4 ganger. Sjekk saltinnholdet ved å smake – den skal være mildt salt, ikke kraftig salt. Hell av vannet og skjær fisken i store biter (fjern bein og skinn).',
        'Forvarm ovnen til 180 °C. Skjær poteter (600 g) i tykke skiver og legg i en langpanne. Finhakk løk (2 stk) og hvitløk (4 fedd), skjær paprika (2 stk, rød og gul) i brede strimler.',
        'Varm olivenolje (4 ss) i en stor stekepanne og stek løk og paprika i 8–10 minutter til myke. Tilsett hvitløk og stek 2 minutter. Tilsett hermetiske tomater (1 boks), kalamata-oliven (100 g, uten stein), en klype sukker og tørket oregano (1 ts). La koke 5 minutter.',
        'Legg potetskivene i en ildfast form. Fordel tomatsaus over. Legg klippfiskbitene oppå og drypp over litt olivenolje. Dekk formen med folie.',
        'Stek i ovnen i 30 minutter med folie. Fjern folie og stek videre 15–20 minutter til fisken er gjennomkokt og potetene er møre.',
        'La hvile 5 minutter. Dryss over hakket fersk persille og server rett fra formen med godt brød.',
      ],
    },
    shoppingList: [
      { item: 'Klippfisk (utvannet)', search: 'klippfisk', amount: '600 g', estimatedPrice: 99, category: 'Fisk' },
      { item: 'Potet', search: 'potet', amount: '600 g', estimatedPrice: 18, category: 'Frukt/grønt' },
      { item: 'Hermetiske tomater', search: 'hermetiske tomater', amount: '1 boks', estimatedPrice: 12, category: 'Tørrvarer' },
      { item: 'Kalamata-oliven', search: 'kalamata oliven', amount: '100 g', estimatedPrice: 28, category: 'Tørrvarer' },
      { item: 'Paprika (rød og gul)', search: 'paprika', amount: '2 stk', estimatedPrice: 20, category: 'Frukt/grønt' },
    ],
  },

  {
    id: 'kveite-smorssaus',
    name: 'Kveite med smørsaus og asparges',
    type: 'fish',
    highProtein: true,
    allergens: ['fisk', 'laktose'],
    tags: ['kveite', 'fisk', 'smørsaus', 'asparges', 'festmat', 'helg', 'norsk'],
    prepTime: 35,
    difficulty: 'middels',
    leftoverFriendly: false,
    vegetarianAlternative: 'Grillet blomkål med smørsaus og asparges',
    recipe: {
      servings: 4,
      steps: [
        'Ta kveitefiletene (4 stk à ca. 180 g) ut av kjøleskap 20 minutter før tilberedning. Tørk grundig med kjøkkenpapir – dette er viktig for god stekeskorpe. Krydre med salt og hvit pepper like før steking.',
        'Lag smørsaus (beurre blanc): finhakk sjalottløk (2 stk) og kok opp med hvitvin (1,5 dl) og hvitvinseddik (2 ss) til nesten innkokt (ca. 3 ss væske igjen). Skru ned til absolutt laveste varme. Tilsett iskald smør (150 g) terning for terning, rør konstant til emulgert og kremig. Sausen må aldri koke – det ødelegger emulsjonen. Smak til med salt, hvit pepper og litt sitronsaft. Hold varm i vannbad.',
        'Bryt asparges (500 g) – bøy dem bakover, de brekker naturlig ved riktig sted. Kok i lettsaltet vann 3–4 minutter til møre men fortsatt sprø og lyse.',
        'Varm en tung stekepanne (helst non-stick eller støpejern) til middels høy varme. Tilsett smør (1 ss) og olje (1 ss). Når smøret slutter å bruse, legg kveitefiletene forsiktig i pannen. Stek 3–4 minutter uten å røre – skinnsiden gir en vakker stekeskorpe. Snu forsiktig og stek 2–3 minutter til. Kveite er ferdig når den flaker seg når du trykker lett.',
        'Legg asparges på varme tallerkener, plasser kveitefileten oppå. Øs smørsaus rundt og over fisken.',
        'Pynt med sitronbåter, frisk dill og kapers. Server umiddelbart – smørsaus skiller seg raskt.',
      ],
    },
    shoppingList: [
      { item: 'Kveitefilet (4 stk)', search: 'kveitefilet', amount: 'ca. 750 g', estimatedPrice: 199, category: 'Fisk' },
      { item: 'Asparges', search: 'asparges', amount: '500 g', estimatedPrice: 55, category: 'Frukt/grønt' },
      { item: 'Smør (kaldt)', search: 'smør', amount: '180 g', estimatedPrice: 38, category: 'Meieri' },
      { item: 'Hvitvin (tørr)', search: 'hvitvin', amount: '1,5 dl', estimatedPrice: 40, category: 'Diverse' },
      { item: 'Sjalottløk', search: 'sjalottløk', amount: '2 stk', estimatedPrice: 10, category: 'Frukt/grønt' },
    ],
  },

  // ── EKSISTERENDE NYE OPPSKRIFTER ──────────────────────────────────────────

  {
    id: 'laks-teriyaki-edamame',
    name: 'Laks teriyaki med edamame og ris',
    type: 'fish',
    highProtein: true,
    allergens: ['fisk', 'gluten', 'soya', 'sesam'],
    tags: ['laks', 'fisk', 'teriyaki', 'japansk', 'edamame', 'ris', 'asiatisk', 'sunn'],
    prepTime: 25,
    difficulty: 'enkel',
    leftoverFriendly: true,
    vegetarianAlternative: 'Tofu teriyaki med edamame og ris',
    recipe: {
      servings: 4,
      steps: [
        'Kok jasminris (300 g): skyll til vannet er klart, ha i kjele med 450 ml vann og ½ ts salt. Kok opp, skru til laveste varme med lokk og la trekke 12 minutter. Skru av og la hvile 10 minutter.',
        'Lag teriyakisaus: bland soyasaus (4 ss), honning (2 ss), riseddik (1 ss) og revet ingefær (1 ts) i en liten bolle. Rør til honningen løser seg opp.',
        'Tørk laksefilet (600 g) og skjær i 4 porsjoner. Krydre med salt og pepper. Varm olje (1 ss) i en stekepanne på middels høy varme. Stek laksen 3 minutter på skinnsiden uten å røre. Snu og stek 2 minutter til.',
        'Hell teriyakisausen over laksen i pannen. La sausen koke og karamellisere i 1–2 minutter under basting (øs sausen over fisken med en skje). Laksen skal få en blank, søtglinsende glasur.',
        'Kok frosne edamamebønner (200 g) etter anvisning, ca. 3–4 minutter. Hell av og dryss over litt salt og sesamolje.',
        'Fordel ris i boller, legg laks med glasur oppå og edamame ved siden av. Dryss over sesamfrø og servér med limebåter.',
      ],
    },
    shoppingList: [
      { item: 'Laksefilet', search: 'laksefilet', amount: '600 g', estimatedPrice: 119, category: 'Fisk' },
      { item: 'Jasminris', search: 'jasminris', amount: '300 g', estimatedPrice: 25, category: 'Tørrvarer' },
      { item: 'Frosne edamamebønner', search: 'edamame', amount: '200 g', estimatedPrice: 35, category: 'Frys' },
      { item: 'Soyasaus', search: 'soyasaus', amount: '4 ss', estimatedPrice: 8, category: 'Tørrvarer' },
      { item: 'Honning', search: 'honning', amount: '2 ss', estimatedPrice: 10, category: 'Tørrvarer' },
      { item: 'Sesamfrø', search: 'sesamfrø', amount: '2 ss', estimatedPrice: 8, category: 'Tørrvarer' },
    ],
  },

  {
    id: 'tunfisksalat-quinoa',
    name: 'Tunfisksalat med quinoa og egg',
    type: 'fish',
    highProtein: true,
    allergens: ['fisk', 'egg', 'sennep'],
    tags: ['tunfisk', 'fisk', 'quinoa', 'egg', 'salat', 'sunn', 'rask', 'proteinrik'],
    prepTime: 20,
    difficulty: 'enkel',
    leftoverFriendly: false,
    vegetarianAlternative: 'Kikertsalat med quinoa og egg',
    recipe: {
      servings: 4,
      steps: [
        'Kok quinoa (250 g): skyll i sil, ha i kjele med 500 ml vann og salt. Kok opp, skru ned og la trekke med lokk i 15 minutter. Løsne med gaffel og avkjøl litt.',
        'Kok egg (4 stk): legg i kokende vann og kok 8 minutter for fast eggeplomme. Avkjøl i kaldt vann, skrell og del i to.',
        'Åpne tunfiskbokser (2 × 160 g avrent), legg i en sil og press ut væsken godt. Ha i en bolle.',
        'Lag dressing: bland olivenolje (3 ss), sitronsaft (2 ss), dijonsennep (1 ts), salt og pepper. Pisk til emulgert.',
        'Ha quinoa, tunfisk, cherry-tomater (200 g delt i to), agurk (½ stk i terninger) og rødløk (¼ stk finhakket) i en stor bolle. Hell over dressingen og vend forsiktig.',
        'Fordel i tallerkener, legg egg-halvdelene over og dryss på fersk persille og gjerne litt kapers.',
      ],
    },
    shoppingList: [
      { item: 'Tunfisk på boks (i vann)', search: 'tunfisk boks', amount: '2 × 160 g', estimatedPrice: 40, category: 'Tørrvarer' },
      { item: 'Quinoa', search: 'quinoa', amount: '250 g', estimatedPrice: 38, category: 'Tørrvarer' },
      { item: 'Egg', search: 'egg', amount: '4 stk', estimatedPrice: 16, category: 'Meieri' },
      { item: 'Cherrytomater', search: 'cherrytomater', amount: '200 g', estimatedPrice: 25, category: 'Frukt/grønt' },
      { item: 'Agurk', search: 'agurk', amount: '½ stk', estimatedPrice: 10, category: 'Frukt/grønt' },
    ],
  },

  {
    id: 'reker-pasta',
    name: 'Rekepasta med hvitløk og sitron',
    type: 'fish',
    highProtein: true,
    allergens: ['fisk', 'skalldyr', 'gluten'],
    tags: ['reker', 'pasta', 'hvitløk', 'sitron', 'sjømat'],
    prepTime: 20,
    difficulty: 'enkel',
    leftoverFriendly: false,
    recipe: {
      servings: 4,
      steps: [
        'Kok linguine (400 g) etter pakningsanvisning til al dente. Spar 1 dl pastavann.',
        'Varm olivenolje i en stor panne på middels varme. Fres 3 finhakkede hvitløkfedd i 1 minutt.',
        'Tilsett pillede reker (400 g) og stek 2 minutter til de er gjennomvarme. Krydre med salt, pepper og chiliflak.',
        'Tilsett den avsilte pastaen og litt pastavann. Rør godt og press over saften av 1 sitron.',
        'Server med finhakket persille og ekstra sitronspalter.',
      ],
    },
    shoppingList: [
      { item: 'Pillede reker', search: 'reker pillede', amount: '400 g', estimatedPrice: 89, category: 'Fisk' },
      { item: 'Linguine', search: 'linguine pasta', amount: '400 g', estimatedPrice: 25, category: 'Tørrvarer' },
      { item: 'Sitron', search: 'sitron', amount: '1 stk', estimatedPrice: 8, category: 'Frukt/grønt' },
      { item: 'Hvitløk', search: 'hvitløk', amount: '3 fedd', estimatedPrice: 5, category: 'Frukt/grønt' },
      { item: 'Persille', search: 'persille fersk', amount: '½ bunt', estimatedPrice: 15, category: 'Frukt/grønt' },
    ],
  },

  {
    id: 'fiskekaker-hjemmelaget',
    name: 'Hjemmelagde fiskekaker med rotmos',
    type: 'fish',
    highProtein: true,
    allergens: ['fisk', 'gluten', 'egg'],
    tags: ['fiskekaker', 'torsk', 'rotmos', 'tradisjonell', 'norsk'],
    prepTime: 40,
    difficulty: 'middels',
    leftoverFriendly: true,
    recipe: {
      servings: 4,
      steps: [
        'Skjær torskefilet (600 g) i biter og kjør i foodprosessor med 1 egg, 2 ss potetmel, salt, pepper og litt revet muskatnøtt.',
        'Form til runde kaker (ca. 8 stk) og stek i smør på middels varme, 4 minutter per side til de er gyldne.',
        'Kok gulrøtter, kålrot og poteter (totalt 600 g) i lettsaltet vann til møre, ca. 20 minutter.',
        'Hell av vannet og mos grønnsakene med smør og litt melk. Smak til med salt og pepper.',
        'Server fiskekakene på rotmos med en klatt rømme og persille.',
      ],
    },
    shoppingList: [
      { item: 'Torskefilet', search: 'torskefilet fersk', amount: '600 g', estimatedPrice: 95, category: 'Fisk' },
      { item: 'Egg', search: 'egg', amount: '1 stk', estimatedPrice: 5, category: 'Meieri' },
      { item: 'Potetmel', search: 'potetmel', amount: '2 ss', estimatedPrice: 10, category: 'Tørrvarer' },
      { item: 'Poteter', search: 'poteter', amount: '300 g', estimatedPrice: 15, category: 'Frukt/grønt' },
      { item: 'Gulrøtter', search: 'gulrøtter', amount: '200 g', estimatedPrice: 12, category: 'Frukt/grønt' },
      { item: 'Kålrot', search: 'kålrot', amount: '200 g', estimatedPrice: 10, category: 'Frukt/grønt' },
      { item: 'Rømme', search: 'rømme', amount: '1 dl', estimatedPrice: 15, category: 'Meieri' },
    ],
  },

  {
    id: 'laks-hvit-bonne-salat',
    name: 'Laks med hvite bønner og pesto',
    type: 'fish',
    highProtein: true,
    allergens: ['fisk', 'nøtter'],
    tags: ['laks', 'bønner', 'pesto', 'sunn', 'salat'],
    prepTime: 20,
    difficulty: 'enkel',
    leftoverFriendly: true,
    recipe: {
      servings: 4,
      steps: [
        'Krydre laksefileter (500 g) med salt og pepper. Stek i olivenolje 3–4 minutter per side.',
        'Skyll og avrent 2 bokser hvite bønner. Bland med 3 ss grønn pesto, saften av ½ sitron og en neve ruccola.',
        'Del laksen i store flak og legg over bønnesalaten.',
        'Dryss over pinjekjerner og server umiddelbart.',
      ],
    },
    shoppingList: [
      { item: 'Laksefilet', search: 'laksefilet', amount: '500 g', estimatedPrice: 99, category: 'Fisk' },
      { item: 'Hvite bønner (boks)', search: 'hvite bønner hermetisk', amount: '2 bokser', estimatedPrice: 30, category: 'Tørrvarer' },
      { item: 'Grønn pesto', search: 'pesto grønn', amount: '3 ss', estimatedPrice: 20, category: 'Tørrvarer' },
      { item: 'Ruccola', search: 'ruccola', amount: '50 g', estimatedPrice: 20, category: 'Frukt/grønt' },
      { item: 'Pinjekjerner', search: 'pinjekjerner', amount: '2 ss', estimatedPrice: 18, category: 'Tørrvarer' },
    ],
  },

  {
    id: 'torsketaco',
    name: 'Fisketaco med torsk og mango-salsa',
    type: 'fish',
    highProtein: true,
    allergens: ['fisk', 'gluten'],
    tags: ['taco', 'torsk', 'mango', 'salsa', 'wrap'],
    prepTime: 25,
    difficulty: 'enkel',
    leftoverFriendly: false,
    recipe: {
      servings: 4,
      steps: [
        'Bland 1 ts spisskummen, 1 ts røkt paprika, salt og pepper. Rull torskefileter (500 g) i krydderblandingen.',
        'Stek fisken i olivenolje 3–4 minutter per side. Del i store flak.',
        'Lag mango-salsa: bland 1 terninget mango, ½ rødløk (finhakket), 1 chili (finhakket), saft av 1 lime og litt koriander.',
        'Varm tortillaer i tørr panne. Fyll med kål, fisk og mango-salsa.',
        'Server med rømme eller gresk yoghurt.',
      ],
    },
    shoppingList: [
      { item: 'Torskefilet', search: 'torskefilet', amount: '500 g', estimatedPrice: 89, category: 'Fisk' },
      { item: 'Tortilla', search: 'tortilla hvete', amount: '8 stk', estimatedPrice: 25, category: 'Tørrvarer' },
      { item: 'Mango', search: 'mango', amount: '1 stk', estimatedPrice: 20, category: 'Frukt/grønt' },
      { item: 'Rødløk', search: 'rødløk', amount: '½ stk', estimatedPrice: 5, category: 'Frukt/grønt' },
      { item: 'Kål (hvit eller rød)', search: 'hodekål', amount: '150 g', estimatedPrice: 10, category: 'Frukt/grønt' },
      { item: 'Lime', search: 'lime', amount: '1 stk', estimatedPrice: 8, category: 'Frukt/grønt' },
      { item: 'Koriander', search: 'koriander fersk', amount: '½ bunt', estimatedPrice: 15, category: 'Frukt/grønt' },
    ],
  },

  {
    id: 'sushi-bowl',
    name: 'Sushi bowl med laks og avokado',
    type: 'fish',
    highProtein: true,
    allergens: ['fisk', 'gluten', 'soya', 'sesam'],
    tags: ['sushi', 'laks', 'avokado', 'ris', 'asiatisk'],
    prepTime: 30,
    difficulty: 'middels',
    leftoverFriendly: false,
    recipe: {
      servings: 4,
      steps: [
        'Kok sushiris (400 g) etter pakningsanvisning. Bland varm ris med 4 ss riseddik, 2 ss sukker og 1 ts salt. La avkjøle.',
        'Skjær fersk laksefilet (400 g) i tynne skiver. (Bruk sashimi-kvalitet eller frys fisken i 24 t og tin i kjøleskap.)',
        'Del 2 avokado i skiver, skjær agurk i tynne strimler.',
        'Fordel ris i boller. Topp med laks, avokado, agurk og edamame.',
        'Dryss over sesamfrø og server med soyasaus, wasabi og ingefær på siden.',
      ],
    },
    shoppingList: [
      { item: 'Laksefilet (fersk/fryst)', search: 'laksefilet', amount: '400 g', estimatedPrice: 89, category: 'Fisk' },
      { item: 'Sushiris', search: 'sushiris', amount: '400 g', estimatedPrice: 30, category: 'Tørrvarer' },
      { item: 'Avokado', search: 'avokado', amount: '2 stk', estimatedPrice: 30, category: 'Frukt/grønt' },
      { item: 'Riseddik', search: 'riseddik', amount: '4 ss', estimatedPrice: 25, category: 'Tørrvarer' },
      { item: 'Edamame (fryst)', search: 'edamame', amount: '150 g', estimatedPrice: 28, category: 'Frys' },
      { item: 'Soyasaus', search: 'soyasaus', amount: '4 ss', estimatedPrice: 20, category: 'Tørrvarer' },
      { item: 'Sesamfrø', search: 'sesamfrø', amount: '2 ss', estimatedPrice: 15, category: 'Tørrvarer' },
      { item: 'Agurk', search: 'agurk', amount: '½ stk', estimatedPrice: 10, category: 'Frukt/grønt' },
    ],
  },

  {
    id: 'fiskegryte-kokos',
    name: 'Fiskegryte med kokos og ingefær',
    type: 'fish',
    highProtein: true,
    allergens: ['fisk', 'skalldyr'],
    tags: ['fiskegryte', 'kokos', 'ingefær', 'curry', 'asiatisk'],
    prepTime: 30,
    difficulty: 'enkel',
    leftoverFriendly: true,
    recipe: {
      servings: 4,
      steps: [
        'Fres finhakket løk, 2 hvitløkfedd og 2 cm fersk ingefær i olje i 3 minutter.',
        'Tilsett 1 ss rød karripasta og stek 1 minutt. Hell i 1 boks kokosmelk og 2 dl fiskekraft.',
        'La koke opp, tilsett torskefilet (500 g) i biter. Kok forsiktig 6–8 minutter.',
        'Smak til med fiskesaus og limesaft. Tilsett eventuelt reker de siste 2 minuttene.',
        'Server med jasminris og fersk koriander.',
      ],
    },
    shoppingList: [
      { item: 'Torskefilet', search: 'torskefilet', amount: '500 g', estimatedPrice: 89, category: 'Fisk' },
      { item: 'Kokosmelk', search: 'kokosmelk', amount: '1 boks', estimatedPrice: 25, category: 'Tørrvarer' },
      { item: 'Rød karripasta', search: 'rød karripasta', amount: '1 ss', estimatedPrice: 20, category: 'Tørrvarer' },
      { item: 'Jasminris', search: 'jasminris', amount: '300 g', estimatedPrice: 20, category: 'Tørrvarer' },
      { item: 'Ingefær', search: 'ingefær fersk', amount: '2 cm', estimatedPrice: 8, category: 'Frukt/grønt' },
      { item: 'Koriander', search: 'koriander fersk', amount: '½ bunt', estimatedPrice: 15, category: 'Frukt/grønt' },
      { item: 'Lime', search: 'lime', amount: '1 stk', estimatedPrice: 8, category: 'Frukt/grønt' },
    ],
  },

  {
    id: 'laks-misoglasert',
    name: 'Misomarinert laks med bok choy og ris',
    type: 'fish',
    highProtein: true,
    allergens: ['fisk', 'gluten', 'soya', 'sesam'],
    tags: ['laks', 'miso', 'japansk', 'bok choy', 'asiatisk'],
    prepTime: 35,
    difficulty: 'middels',
    leftoverFriendly: false,
    recipe: {
      servings: 4,
      steps: [
        'Bland 3 ss hvit miso, 2 ss mirin, 1 ss soyasaus og 1 ss honning til en marinade.',
        'Mariner laksefileter (500 g) i 20 minutter.',
        'Sett ovnen på 220°C. Legg laksen på bakepapir og stek 12–15 minutter til glasuren er karamellisert.',
        'Del bok choy på langs og fres i sesamolje med et fedd hvitløk, 3–4 minutter.',
        'Server laks og bok choy over dampet ris. Dryss over sesamfrø.',
      ],
    },
    shoppingList: [
      { item: 'Laksefilet', search: 'laksefilet', amount: '500 g', estimatedPrice: 99, category: 'Fisk' },
      { item: 'Hvit miso', search: 'miso paste', amount: '3 ss', estimatedPrice: 35, category: 'Tørrvarer' },
      { item: 'Mirin', search: 'mirin', amount: '2 ss', estimatedPrice: 30, category: 'Tørrvarer' },
      { item: 'Bok choy', search: 'bok choy pak choi', amount: '4 stk', estimatedPrice: 40, category: 'Frukt/grønt' },
      { item: 'Jasminris', search: 'jasminris', amount: '300 g', estimatedPrice: 20, category: 'Tørrvarer' },
      { item: 'Sesamolje', search: 'sesamolje', amount: '1 ss', estimatedPrice: 20, category: 'Tørrvarer' },
    ],
  },

  {
    id: 'makrell-tomat',
    name: 'Ovnsbakt makrell med tomat og urter',
    type: 'fish',
    highProtein: true,
    allergens: ['fisk'],
    tags: ['makrell', 'tomat', 'ovn', 'norsk', 'tradisjonell'],
    prepTime: 30,
    difficulty: 'enkel',
    leftoverFriendly: false,
    recipe: {
      servings: 4,
      steps: [
        'Sett ovnen på 200°C. Rens 2 hele makreller, skjær 3–4 snitt på siden.',
        'Gni inn med salt, pepper, hvitløk og frisk timian. Fyll buken med sitronskiver.',
        'Legg på en ildfast form, surround med halverte cherrytomater og litt olivenolje.',
        'Stek i 20–25 minutter til fiskekjøttet lett løsner fra bena.',
        'Server med nybakt brød og en grønn salat.',
      ],
    },
    shoppingList: [
      { item: 'Hel makrell', search: 'makrell fersk hel', amount: '2 stk', estimatedPrice: 60, category: 'Fisk' },
      { item: 'Cherrytomater', search: 'cherrytomater', amount: '250 g', estimatedPrice: 30, category: 'Frukt/grønt' },
      { item: 'Sitron', search: 'sitron', amount: '1 stk', estimatedPrice: 8, category: 'Frukt/grønt' },
      { item: 'Timian', search: 'timian fersk', amount: '4 kvister', estimatedPrice: 12, category: 'Frukt/grønt' },
      { item: 'Brød', search: 'landbrød', amount: '1 stk', estimatedPrice: 30, category: 'Tørrvarer' },
    ],
  },

  {
    id: 'scampi-hvitvin',
    name: 'Scampi i hvitvin med aglio e olio',
    type: 'fish',
    highProtein: true,
    allergens: ['fisk', 'skalldyr', 'gluten'],
    tags: ['scampi', 'hvitvin', 'pasta', 'italiensk', 'hvitløk'],
    prepTime: 25,
    difficulty: 'middels',
    leftoverFriendly: false,
    recipe: {
      servings: 4,
      steps: [
        'Kok spaghetti (400 g) al dente. Spar 1 dl pastavann.',
        'Varm rikelig med olivenolje i en stor panne. Fres 4 hvitløkfedd (skivet) og chiliflak 2 minutter.',
        'Tilsett scampi (500 g) og stek 2 minutter per side. Ha i 1 dl hvitvin og la koke inn 2 minutter.',
        'Bland inn spaghettien og litt pastavann til sausen er kremete.',
        'Server med finhakket persille og sitronbåter.',
      ],
    },
    shoppingList: [
      { item: 'Scampi (pillede)', search: 'scampi pillede', amount: '500 g', estimatedPrice: 110, category: 'Fisk' },
      { item: 'Spaghetti', search: 'spaghetti', amount: '400 g', estimatedPrice: 22, category: 'Tørrvarer' },
      { item: 'Hvitvin (tørr)', search: 'hvitvin', amount: '1 dl', estimatedPrice: 30, category: 'Diverse' },
      { item: 'Hvitløk', search: 'hvitløk', amount: '4 fedd', estimatedPrice: 5, category: 'Frukt/grønt' },
      { item: 'Persille', search: 'persille fersk', amount: '½ bunt', estimatedPrice: 15, category: 'Frukt/grønt' },
      { item: 'Sitron', search: 'sitron', amount: '1 stk', estimatedPrice: 8, category: 'Frukt/grønt' },
    ],
  },

  {
    id: 'torsk-kokos-brod',
    name: 'Torsk med kokoskorpe og brokkolipuré',
    type: 'fish',
    highProtein: true,
    allergens: ['fisk', 'gluten'],
    tags: ['torsk', 'kokos', 'brokkoli', 'ovn'],
    prepTime: 35,
    difficulty: 'middels',
    leftoverFriendly: false,
    recipe: {
      servings: 4,
      steps: [
        'Bland 50 g panko, 30 g kokosmasse, 1 ss smeltet smør, salt og pepper. Press blandingen på torskefileter (600 g).',
        'Stek i ovn på 200°C i 15 minutter til korpen er gyllen.',
        'Kok brokkoli (400 g) til veldig mør. Blitze med 1 ss smør, salt, pepper og litt fløte til en silkemyk puré.',
        'Server torsk på brokkolipureen med sitronbåter ved siden av.',
      ],
    },
    shoppingList: [
      { item: 'Torskefilet', search: 'torskefilet', amount: '600 g', estimatedPrice: 95, category: 'Fisk' },
      { item: 'Panko', search: 'panko brødsmuler', amount: '50 g', estimatedPrice: 20, category: 'Tørrvarer' },
      { item: 'Kokosmasse (revet)', search: 'revet kokos', amount: '30 g', estimatedPrice: 15, category: 'Tørrvarer' },
      { item: 'Brokkoli', search: 'brokkoli', amount: '400 g', estimatedPrice: 25, category: 'Frukt/grønt' },
      { item: 'Fløte', search: 'matfløte', amount: '0.5 dl', estimatedPrice: 10, category: 'Meieri' },
    ],
  },

  {
    id: 'sjomatrisotto',
    name: 'Sjømatrisotto med reker og blåskjell',
    type: 'fish',
    highProtein: true,
    allergens: ['fisk', 'skalldyr', 'laktose'],
    tags: ['risotto', 'reker', 'blåskjell', 'sjømat', 'italiensk'],
    prepTime: 45,
    difficulty: 'avansert',
    leftoverFriendly: false,
    recipe: {
      servings: 4,
      steps: [
        'Varm 1 l fiskekraft i en kjele og hold den varm.',
        'Fres finhakket løk og 2 hvitløkfedd i smør til myke. Tilsett arborioris (300 g) og stek 2 minutter.',
        'Hell i 1 dl hvitvin og rør til det er absorbert. Øs inn kraft, én øse om gangen, og rør kontinuerlig i 18–20 minutter.',
        'Rens blåskjell (500 g) og damp i hvitvin til de åpner seg. Plukk ut kjøttet.',
        'Rør smør (30 g) og parmesan (50 g) inn i risottoen. Tilsett reker og blåskjellkjøtt. Smak til.',
        'Server umiddelbart med persille og sitron.',
      ],
    },
    shoppingList: [
      { item: 'Pillede reker', search: 'reker pillede', amount: '200 g', estimatedPrice: 65, category: 'Fisk' },
      { item: 'Blåskjell', search: 'blåskjell', amount: '500 g', estimatedPrice: 55, category: 'Fisk' },
      { item: 'Arborioris', search: 'risottoris arborio', amount: '300 g', estimatedPrice: 35, category: 'Tørrvarer' },
      { item: 'Fiskekraft', search: 'fiskekraft fond', amount: '1 liter', estimatedPrice: 40, category: 'Tørrvarer' },
      { item: 'Hvitvin', search: 'hvitvin', amount: '2 dl', estimatedPrice: 35, category: 'Diverse' },
      { item: 'Parmesan', search: 'parmesan', amount: '50 g', estimatedPrice: 32, category: 'Meieri' },
    ],
  },

  {
    id: 'laks-salat-varm',
    name: 'Varm laksesalat med poteter og sennepsdressing',
    type: 'fish',
    highProtein: true,
    allergens: ['fisk', 'sennep', 'egg'],
    tags: ['laks', 'salat', 'poteter', 'sennep', 'varm salat'],
    prepTime: 25,
    difficulty: 'enkel',
    leftoverFriendly: true,
    recipe: {
      servings: 4,
      steps: [
        'Kok poteter (500 g) til møre, halver dem og hold varme.',
        'Stek laksefileter (500 g) i smør, 3–4 minutter per side. Flak opp kjøttet.',
        'Lag dressing: bland 2 ss grov sennep, 1 ss honning, 2 ss olivenolje, 1 ss eplecidereddik og salt.',
        'Bland poteter, lakseflak, grønnkål (100 g), rødløk i ringer og halverte kokte egg (4 stk).',
        'Hell over dressingen og server med en gang.',
      ],
    },
    shoppingList: [
      { item: 'Laksefilet', search: 'laksefilet', amount: '500 g', estimatedPrice: 99, category: 'Fisk' },
      { item: 'Poteter', search: 'poteter', amount: '500 g', estimatedPrice: 20, category: 'Frukt/grønt' },
      { item: 'Egg', search: 'egg', amount: '4 stk', estimatedPrice: 20, category: 'Meieri' },
      { item: 'Grønnkål', search: 'grønnkål', amount: '100 g', estimatedPrice: 20, category: 'Frukt/grønt' },
      { item: 'Rødløk', search: 'rødløk', amount: '1 stk', estimatedPrice: 8, category: 'Frukt/grønt' },
      { item: 'Grov sennep', search: 'sennep grov', amount: '2 ss', estimatedPrice: 15, category: 'Tørrvarer' },
    ],
  },

  {
    id: 'orretsashimi-salat',
    name: 'Ørret gravlaks-salat med sennepsdressing',
    type: 'fish',
    highProtein: true,
    allergens: ['fisk', 'sennep', 'gluten'],
    tags: ['ørret', 'gravlaks', 'salat', 'sennep', 'norsk'],
    prepTime: 15,
    difficulty: 'enkel',
    leftoverFriendly: false,
    recipe: {
      servings: 4,
      steps: [
        'Lag sennepsdressing: bland 2 ss grov sennep, 1 ss honning, 2 ss eplecidereddik og 3 ss olivenolje. Smak til med salt og pepper.',
        'Bland blandet salat (100 g), agurk (skivet), reddiker og avokado (skivet) i en stor bolle.',
        'Legg gravlaks (300 g) i fine skiver over salaten.',
        'Dryss over kapers og dill. Drypp sennepsdressingen over og server med rugbrød.',
      ],
    },
    shoppingList: [
      { item: 'Gravlaks', search: 'gravlaks ørret', amount: '300 g', estimatedPrice: 85, category: 'Fisk' },
      { item: 'Blandet salat', search: 'salat blanding', amount: '100 g', estimatedPrice: 25, category: 'Frukt/grønt' },
      { item: 'Avokado', search: 'avokado', amount: '1 stk', estimatedPrice: 18, category: 'Frukt/grønt' },
      { item: 'Agurk', search: 'agurk', amount: '½ stk', estimatedPrice: 10, category: 'Frukt/grønt' },
      { item: 'Kapers', search: 'kapers', amount: '2 ss', estimatedPrice: 20, category: 'Tørrvarer' },
      { item: 'Rugbrød', search: 'rugbrød', amount: '4 skiver', estimatedPrice: 15, category: 'Tørrvarer' },
      { item: 'Grov sennep', search: 'sennep grov', amount: '2 ss', estimatedPrice: 15, category: 'Tørrvarer' },
    ],
  },

  {
    id: 'sei-sous-vide-restaurant',
    name: 'Sei sous-vide med beurre blanc og grønnsaker',
    type: 'fish',
    highProtein: true,
    allergens: ['fisk', 'laktose'],
    tags: ['sei', 'sous-vide', 'restaurant', 'løkløk', 'avansert'],
    prepTime: 70,
    difficulty: 'avansert',
    leftoverFriendly: false,
    recipe: {
      servings: 4,
      steps: [
        'Vakuumpakk seifileter (4 × 120 g) med smør, timian, sitronsaft, salt og pepper. Seitid: 45 minutter på 56°C (eller immersion blender med varmeregulert vannbad).',
        'Lag beurre blanc: reduser hvitt vin (1 dl) og hvitvinseddik (2 ss) med finhakket sjalottløk (2) ned til ca. 2 ss. Fjern fra varme.',
        'Rør inn kaldt smør (150 g i terninger) litt etter litt. Passér gjennom sil. Smak til med salt og hvit pepper.',
        'Dampetilbered: carrots (8 baby), fennikel (1 ball skåret), og små poteter (200 g) i 8–10 minutter til akkurat møre.',
        'Tørk seifileterne, rist kort i panne med smør til gullbrun. Server med beurre blanc, dampet grønnsaker og frisk dill.',
      ],
    },
    shoppingList: [
      { item: 'Seifileter', search: 'seifileter', amount: '480 g', estimatedPrice: 95, category: 'Fisk' },
      { item: 'Hvitt vin', search: 'hvitt vin', amount: '2 dl', estimatedPrice: 40, category: 'Annet' },
      { item: 'Hvitvinseddik', search: 'hvitvinseddik', amount: '2 ss', estimatedPrice: 8, category: 'Tørrvarer' },
      { item: 'Smør (høy kvalitet)', search: 'smør', amount: '150 g', estimatedPrice: 35, category: 'Meieri' },
      { item: 'Sjalottløk', search: 'sjalottløk', amount: '2 stk', estimatedPrice: 8, category: 'Frukt/grønt' },
      { item: 'Gulrot baby', search: 'gulrot baby', amount: '8 stk', estimatedPrice: 12, category: 'Frukt/grønt' },
      { item: 'Fennikel', search: 'fennikel', amount: '1 ball', estimatedPrice: 15, category: 'Frukt/grønt' },
    ],
  },

  {
    id: 'torsk-asiatisk-papir',
    name: 'Torsk dampet i papir med asiatiske smak',
    type: 'fish',
    highProtein: true,
    allergens: ['fisk', 'gluten', 'soya'],
    tags: ['torsk', 'asiatisk', 'papirdampet', 'lemongrass', 'avansert'],
    prepTime: 45,
    difficulty: 'avansert',
    leftoverFriendly: false,
    recipe: {
      servings: 4,
      steps: [
        'Lag marinade: bland 4 ss soyasaus, 2 ss riseddik, 1 ss sesamolje, 2 cm revet ingefær, 2 finhakkede hvitløkfedd og 1 finhakket rød chili. Delt i to deler.',
        'Klipp 4 ark bakepapir (30×40 cm) og legg den fine siden opp. Legg ½ lemongrass, ½ pakchoi og 1 torskefilet (150 g) på hver.',
        'Drysle halvparten av marinaden over fisken. Lukk papirpakker: fold ender inn og krim lufttett.',
        'Dampetilbered i ovn på 200°C i 12–15 minutter, eller over kokende vann i 15 minutter.',
        'Server i åpne papirpakker (vær forsiktig med dampen!) og dryss gjenværende marinade og frisk koriander over.',
      ],
    },
    shoppingList: [
      { item: 'Torskefilet', search: 'torskefilet', amount: '600 g', estimatedPrice: 120, category: 'Fisk' },
      { item: 'Lemongrass', search: 'lemongrass', amount: '2 stk', estimatedPrice: 10, category: 'Frukt/grønt' },
      { item: 'Pakchoi/bok choi', search: 'pakchoi', amount: '2 stk', estimatedPrice: 12, category: 'Frukt/grønt' },
      { item: 'Soyasaus', search: 'soyasaus', amount: '4 ss', estimatedPrice: 15, category: 'Tørrvarer' },
      { item: 'Riseddik', search: 'riseddik', amount: '2 ss', estimatedPrice: 12, category: 'Tørrvarer' },
      { item: 'Sesamolje', search: 'sesamolje', amount: '1 ss', estimatedPrice: 15, category: 'Tørrvarer' },
      { item: 'Bakepapir', search: 'bakepapir', amount: '1 pakke', estimatedPrice: 8, category: 'Annet' },
    ],
  },

];
