// meals-vegan.js — veganske oppskrifter (ingen animalske produkter)
// For å legge til en ny oppskrift: kopier én blokk og endre feltene.
// highProtein: true = > ~25 g protein per porsjon

export const VEGAN_MEALS = [

  {
    id: 'dal-tadka',
    name: 'Dal tadka med basmatiris',
    type: 'vegan',
    highProtein: true,
    allergens: [],
    tags: ['dal', 'linser', 'vegan', 'indisk', 'ris', 'belgfrukter', 'sunn', 'rask'],
    prepTime: 30,
    difficulty: 'enkel',
    leftoverFriendly: true,
    vegetarianAlternative: null,
    recipe: {
      servings: 4,
      steps: [
        'Start basmatiris (300 g): skyll til vannet er klart, ha i kjele med 600 ml vann og salt. Kok opp, skru til laveste varme med lokk, la trekke 12 minutter. Skru av og la hvile 10 minutter.',
        'Skyll røde og gule linser (300 g totalt) i kaldt vann. Ha i en stor kjele med vann (1 l) og kok opp. Skum av skummet som dannes de første minuttene. Skru ned til middels varme og kok 15–18 minutter til linsene er møre og begynner å løse seg opp.',
        'Finhakk løk (1 stk), hvitløk (4 fedd) og ingefær (2 cm). Varm plantebasert olje (3 ss) i en stekepanne på høy varme. Tilsett sennepsfrø (1 ts) – vent til de begynner å poppe. Tilsett løk og stek 6–8 minutter til gyllen.',
        'Tilsett hvitløk og ingefær og stek 1 minutt. Rør inn gurkemeie (1 ts), spisskummen (1 ts), korianderfrø (1 ts) og cayennepepper (½ ts). Stek 1–2 minutter til krydderne dufter kraftig.',
        'Hell krydderblanding over i linsene og rør godt. Tilsett hermetiske tomater (1 boks) og kok videre 5–8 minutter til sausen har satt seg. Smak til med salt og limesaft (½ lime).',
        'Server over basmatiris. Dryss over fersk koriander og server med ekstra lime ved siden av.',
      ],
    },
    shoppingList: [
      { item: 'Røde linser', search: 'røde linser', amount: '300 g', estimatedPrice: 28, category: 'Tørrvarer' },
      { item: 'Basmatiris', search: 'basmatiris', amount: '300 g', estimatedPrice: 22, category: 'Tørrvarer' },
      { item: 'Hermetiske tomater', search: 'hermetiske tomater', amount: '1 boks', estimatedPrice: 12, category: 'Tørrvarer' },
      { item: 'Løk', search: 'løk', amount: '1 stk', estimatedPrice: 5, category: 'Frukt/grønt' },
      { item: 'Fersk koriander', search: 'koriander fersk', amount: '½ bunt', estimatedPrice: 12, category: 'Frukt/grønt' },
    ],
  },

  {
    id: 'vegan-chili',
    name: 'Vegansk chili sin carne',
    type: 'vegan',
    highProtein: true,
    allergens: [],
    tags: ['chili', 'vegan', 'meksikansk', 'bønner', 'belgfrukter', 'krydret', 'restemat'],
    prepTime: 35,
    difficulty: 'enkel',
    leftoverFriendly: true,
    vegetarianAlternative: null,
    recipe: {
      servings: 4,
      steps: [
        'Finhakk løk (1 stor) og hvitløk (3 fedd). Skjær paprika (2 stk) i terninger.',
        'Varm olje (2 ss) i en stor gryte på middels varme. Stek løk i 5 minutter til myk. Tilsett hvitløk og paprika og stek 3 minutter til.',
        'Rør inn chilipulver (2 ts), spisskummen (1 ts), røkt paprika (1 ts), oregano (1 ts) og kakaopulver (1 ss – gir dybde og fylde). Stek krydderne i 1 minutt.',
        'Tilsett hermetiske tomater (2 bokser), avrent kidneybønner (2 bokser à 400 g), avrent mais (1 boks) og grønnsakskraft (2 dl). Rør godt og kok opp.',
        'Skru ned til middels svak varme og la chilien småkoke uten lokk i 20 minutter, rør jevnlig. Sausen skal tykne. Smak til med salt, pepper og limesaft.',
        'Server med kokt ris eller tortillachips. Topp med avokado, fersk koriander og jalapeños.',
      ],
    },
    shoppingList: [
      { item: 'Kidneybønner (2 bokser)', search: 'kidneybønner boks', amount: '2 × 400 g', estimatedPrice: 28, category: 'Tørrvarer' },
      { item: 'Hermetiske tomater', search: 'hermetiske tomater', amount: '2 bokser', estimatedPrice: 24, category: 'Tørrvarer' },
      { item: 'Mais (boks)', search: 'mais boks', amount: '1 boks', estimatedPrice: 12, category: 'Tørrvarer' },
      { item: 'Paprika (rød)', search: 'paprika rød', amount: '2 stk', estimatedPrice: 20, category: 'Frukt/grønt' },
      { item: 'Avokado', search: 'avokado', amount: '2 stk', estimatedPrice: 30, category: 'Frukt/grønt' },
    ],
  },

  {
    id: 'tofu-cashew-wok',
    name: 'Tofu stir-fry med cashewnøtter og nudler',
    type: 'vegan',
    highProtein: true,
    allergens: ['gluten', 'soya', 'nøtter', 'sesam'],
    tags: ['tofu', 'wok', 'vegan', 'asiatisk', 'cashew', 'nøtter', 'nudler'],
    prepTime: 25,
    difficulty: 'enkel',
    leftoverFriendly: false,
    vegetarianAlternative: null,
    recipe: {
      servings: 4,
      steps: [
        'Press tofuen (400 g, fast type): pakk inn i kjøkkenhåndkle og legg en tung gjenstand oppå i 15 minutter. Skjær i terninger.',
        'Kok nudler (300 g, udon eller lo mein) etter anvisning. Hell av og skyll med kaldt vann for å stoppe kokingen. Sett til side.',
        'Rist cashewnøtter (80 g) i en tørr panne på middels varme i 3–4 minutter til gylne og duftende. Hold øye med dem – de svir fort. Sett til side.',
        'Varm olje (2 ss) i en wok på høy varme. Stek tofuterningene 3–4 minutter per side uten å røre til gylne. Ta ut og sett til side.',
        'I samme wok: stek hvitløk (3 fedd, finhakket) og ingefær (2 cm, revet) i 30 sekunder. Tilsett grønnsaker etter behov (brokkoli, gulrot, paprika) og wok 3–4 minutter. Legg i nudlene og tilsett soyasaus (3 ss), sesamolje (1 ts) og sriracha (1 ts). Rør raskt.',
        'Legg tofu tilbake i woken og bland forsiktig. Server umiddelbart med cashewnøtter og sesamfrø drysset over.',
      ],
    },
    shoppingList: [
      { item: 'Fast tofu', search: 'tofu fast', amount: '400 g', estimatedPrice: 35, category: 'Tørrvarer' },
      { item: 'Udon-nudler', search: 'udon nudler', amount: '300 g', estimatedPrice: 28, category: 'Tørrvarer' },
      { item: 'Cashewnøtter', search: 'cashewnøtter', amount: '80 g', estimatedPrice: 30, category: 'Tørrvarer' },
      { item: 'Soyasaus', search: 'soyasaus', amount: '3 ss', estimatedPrice: 8, category: 'Tørrvarer' },
      { item: 'Brokkoli', search: 'brokkoli', amount: '1 hode', estimatedPrice: 25, category: 'Frukt/grønt' },
    ],
  },

  {
    id: 'buddha-bowl',
    name: 'Vegansk Buddha bowl med hummus og quinoa',
    type: 'vegan',
    highProtein: true,
    allergens: ['sesam'],
    tags: ['buddha bowl', 'vegan', 'quinoa', 'hummus', 'sunn', 'fargerik', 'rask'],
    prepTime: 25,
    difficulty: 'enkel',
    leftoverFriendly: false,
    vegetarianAlternative: null,
    recipe: {
      servings: 4,
      steps: [
        'Kok quinoa (300 g): skyll til vannet er klart, ha i kjele med 600 ml vann og salt. Kok opp, skru ned og la trekke med lokk i 15 minutter. Løsne med gaffel og avkjøl litt.',
        'Forvarm ovnen til 200 °C. Skjær søtpotet (500 g) i terninger og kikerter (1 boks, avrent) i en langpanne. Dryss over olivenolje, røkt paprika, salt og pepper. Stek 20–25 minutter til søtpotet er mør og kikertene er lett sprø.',
        'Kok frosne edamamebønner (200 g) etter anvisning. Skjær agurk (½ stk) og avokado (2 stk) i skiver.',
        'Bland hummus (200 g) med litt sitronsaft og vann til ønsket konsistens. Smak til med salt.',
        'Rist gresskarkjerner (3 ss) i en tørr panne til de popper og er lett gylne.',
        'Bygg bowlen: start med quinoa som base, legg søtpotet, kikerter, edamame, agurk og avokado i seksjoner rundt. Legg en god skje hummus i midten. Dryss over gresskarkjerner og drypp over tahini og sitronsaft.',
      ],
    },
    shoppingList: [
      { item: 'Quinoa', search: 'quinoa', amount: '300 g', estimatedPrice: 45, category: 'Tørrvarer' },
      { item: 'Søtpotet', search: 'søtpotet', amount: '500 g', estimatedPrice: 28, category: 'Frukt/grønt' },
      { item: 'Kikerter (boks)', search: 'kikerter boks', amount: '400 g', estimatedPrice: 18, category: 'Tørrvarer' },
      { item: 'Avokado', search: 'avokado', amount: '2 stk', estimatedPrice: 30, category: 'Frukt/grønt' },
      { item: 'Hummus', search: 'hummus', amount: '200 g', estimatedPrice: 25, category: 'Tørrvarer' },
    ],
  },

  {
    id: 'linsebolognese-vegan',
    name: 'Vegansk linsebolognese med pasta',
    type: 'vegan',
    highProtein: true,
    allergens: ['gluten', 'selleri'],
    tags: ['linsebolognese', 'vegan', 'pasta', 'linser', 'italiensk', 'belgfrukter'],
    prepTime: 35,
    difficulty: 'enkel',
    leftoverFriendly: true,
    vegetarianAlternative: null,
    recipe: {
      servings: 4,
      steps: [
        'Finhakk løk (1 stor), hvitløk (3 fedd), gulrot (1 stk) og selleri (1 stilk) veldig fint – dette er den klassiske soffritto-basen.',
        'Varm olivenolje (2 ss) i en bred gryte på middels varme. Stek løk, gulrot og selleri i 8–10 minutter under jevnlig omrøring til grønnsakene er myke og søte. Tilsett hvitløk og stek 1 minutt.',
        'Tilsett tomatpuré (2 ss) og rør inn i 2 minutter. Skru opp varmen og tilsett grønne eller brune linser (300 g, skylte). Rør slik at linsene dekkes av olje og tomat.',
        'Hell over hermetiske tomater (2 bokser à 400 g) og grønnsakskraft (3 dl). Rør godt og kok opp.',
        'Skru ned til svak varme og la bolognesen småkoke med halvt lokk i 25 minutter til linsene er møre og sausen er tyknet. Rør jevnlig og tilsett litt vann om det koker tørt. Smak til med salt, pepper og tørket oregano.',
        'Kok pasta (400 g) etter anvisning. Server pastaen toppet med linsebolognese og dryss over gjærnflak (næringsgjær) i stedet for parmesan.',
      ],
    },
    shoppingList: [
      { item: 'Grønne/brune linser', search: 'brune linser', amount: '300 g', estimatedPrice: 22, category: 'Tørrvarer' },
      { item: 'Fullkornspasta', search: 'fullkornspasta', amount: '400 g', estimatedPrice: 28, category: 'Tørrvarer' },
      { item: 'Hermetiske tomater', search: 'hermetiske tomater', amount: '2 bokser', estimatedPrice: 24, category: 'Tørrvarer' },
      { item: 'Gulrot', search: 'gulrot', amount: '1 stk', estimatedPrice: 5, category: 'Frukt/grønt' },
      { item: 'Næringsgjær (gjærnflak)', search: 'næringsgjær', amount: '2 ss', estimatedPrice: 15, category: 'Tørrvarer' },
    ],
  },

  {
    id: 'thai-gron-curry-vegan',
    name: 'Vegansk thai-grønn curry med tofu og jasminris',
    type: 'vegan',
    highProtein: true,
    allergens: ['gluten', 'soya'],
    tags: ['thai', 'curry', 'vegan', 'tofu', 'kokosmelk', 'asiatisk', 'krydret'],
    prepTime: 30,
    difficulty: 'enkel',
    leftoverFriendly: true,
    vegetarianAlternative: null,
    recipe: {
      servings: 4,
      steps: [
        'Start jasminris (300 g): skyll til vannet er klart, ha i kjele med 450 ml vann og salt. Kok opp, skru til laveste varme med lokk og la trekke 12 minutter. Skru av og la hvile 10 minutter.',
        'Press og terning fast tofu (400 g). Varm olje (2 ss) i en wok på høy varme. Stek tofuterningene 3–4 minutter uten å røre til gylne. Ta ut og sett til side.',
        'I samme wok: tilsett grønn karripasta (2–3 ss, sjekk at den er vegansk) og stek i 1–2 minutter til den dufter og er lett mørkere. Rør konstant.',
        'Hell over kokosmelk (2 bokser à 400 ml) og rør godt. Tilsett fiskesaus (utelat eller bytt med soyasaus for 100 % vegansk), limesaft (2 ss) og palmesukker eller brunt sukker (1 ts).',
        'Tilsett grønnsaker: baby mais, paprika i strimler og sukkererter. Kok 4–5 minutter til grønnsakene er møre men sprø. Legg tofuen tilbake i gryten og varm opp.',
        'Smak til – currien skal balansere søtt, salt, surt og sterkt. Server over jasminris med fersk Thai-basilikum og limebåter.',
      ],
    },
    shoppingList: [
      { item: 'Fast tofu', search: 'tofu fast', amount: '400 g', estimatedPrice: 35, category: 'Tørrvarer' },
      { item: 'Kokosmelk', search: 'kokosmelk', amount: '2 × 400 ml', estimatedPrice: 44, category: 'Tørrvarer' },
      { item: 'Grønn karripasta (vegansk)', search: 'grønn karripasta', amount: '3 ss', estimatedPrice: 18, category: 'Tørrvarer' },
      { item: 'Jasminris', search: 'jasminris', amount: '300 g', estimatedPrice: 25, category: 'Tørrvarer' },
      { item: 'Sukkererter', search: 'sukkererter', amount: '100 g', estimatedPrice: 18, category: 'Frukt/grønt' },
    ],
  },

  {
    id: 'kikert-shawarma',
    name: 'Kikert shawarma med pita og tahini',
    type: 'vegan',
    highProtein: true,
    allergens: ['gluten', 'sesam'],
    tags: ['shawarma', 'kikerter', 'vegan', 'pita', 'midtøsten', 'tahini', 'belgfrukter'],
    prepTime: 30,
    difficulty: 'enkel',
    leftoverFriendly: false,
    vegetarianAlternative: null,
    recipe: {
      servings: 4,
      steps: [
        'Forvarm ovnen til 200 °C. Bland avrent kikerter (2 bokser à 400 g) med olivenolje (3 ss), spisskummen (2 ts), koriander (1 ts), gurkemeie (½ ts), paprika (1 ts), hvitløkpulver (1 ts), salt og pepper. Vend godt til alle kikertene er dekket.',
        'Spread kikerter i et enkelt lag på en stekeplate med bakepapir. Stek 20–25 minutter til sprø og gylne. Ryst brettet halvveis.',
        'Lag tahini-saus: bland tahini (4 ss) med hvitløk (1 fedd, presset), sitronsaft (3 ss), vann (3–4 ss) og salt. Rør til glatt og kremig konsistens. Tilsett mer vann for ønsket tykkelse.',
        'Skjær tomat (2 stk) i skiver og agurk (½ stk) i tynne skiver. Riv salat (½ hode) grovt. Skjær rødløk (½ stk) i tynne halvmåner.',
        'Varm pitabrød (4 stk) i en tørr panne, 30 sekunder per side.',
        'Fordel salat, tomat, agurk og rødløk på pitaen. Legg de sprø kikertene over og drypp rikelig med tahini-saus over alt. Brett sammen og server umiddelbart.',
      ],
    },
    shoppingList: [
      { item: 'Kikerter (2 bokser)', search: 'kikerter boks', amount: '2 × 400 g', estimatedPrice: 36, category: 'Tørrvarer' },
      { item: 'Pitabrød', search: 'pitabrød', amount: '4 stk', estimatedPrice: 25, category: 'Tørrvarer' },
      { item: 'Tahini', search: 'tahini', amount: '4 ss', estimatedPrice: 20, category: 'Tørrvarer' },
      { item: 'Tomat', search: 'tomat', amount: '2 stk', estimatedPrice: 14, category: 'Frukt/grønt' },
      { item: 'Agurk', search: 'agurk', amount: '½ stk', estimatedPrice: 8, category: 'Frukt/grønt' },
    ],
  },

  {
    id: 'vegan-pad-thai',
    name: 'Vegansk pad thai med risnudler og tofu',
    type: 'vegan',
    highProtein: true,
    allergens: ['gluten', 'soya', 'nøtter', 'sesam'],
    tags: ['pad thai', 'vegan', 'thai', 'risnudler', 'tofu', 'asiatisk', 'peanøtter'],
    prepTime: 30,
    difficulty: 'enkel',
    leftoverFriendly: false,
    vegetarianAlternative: null,
    recipe: {
      servings: 4,
      steps: [
        'Bløtlegg risnudler (300 g) i lunkent vann i 20 minutter til myke men fortsatt litt faste. Hell av og sett til side.',
        'Lag pad thai-saus: bland tamarindpasta (3 ss), soyasaus (3 ss), palmesukker (2 ss, eller brunt sukker), og litt sriracha (1 ts). Rør til sukkeret løser seg.',
        'Press og terning fast tofu (400 g). Varm olje (2 ss) i en wok på absolutt høyeste varme. Stek tofuterningene 4–5 minutter uten å røre til gylne og sprø. Ta ut.',
        'I samme wok: stek hvitløk (3 fedd, finhakket) og vårløk (4 stk, hakket) i 1 minutt. Tilsett de bløtlagte nudlene og hell over sausen. Wok raskt i 2–3 minutter til nudlene er varme og dekket av saus.',
        'Legg tofuen tilbake og tilsett bønnespirer (100 g). Wok 1 minutt til alt er gjennomvarmt.',
        'Server umiddelbart med usaltede peanøtter (50 g, grovt hakket), limebåter, fersk koriander og rød chili over.',
      ],
    },
    shoppingList: [
      { item: 'Risnudler (brede)', search: 'risnudler', amount: '300 g', estimatedPrice: 28, category: 'Tørrvarer' },
      { item: 'Fast tofu', search: 'tofu fast', amount: '400 g', estimatedPrice: 35, category: 'Tørrvarer' },
      { item: 'Tamarindpasta', search: 'tamarind', amount: '3 ss', estimatedPrice: 22, category: 'Tørrvarer' },
      { item: 'Usaltede peanøtter', search: 'peanøtter', amount: '50 g', estimatedPrice: 12, category: 'Tørrvarer' },
      { item: 'Bønnespirer', search: 'bønnespirer', amount: '100 g', estimatedPrice: 15, category: 'Frukt/grønt' },
    ],
  },

  {
    id: 'sotpotet-bonne-enchiladas',
    name: 'Svarte bønner og søtpotet enchiladas',
    type: 'vegan',
    highProtein: true,
    allergens: ['gluten'],
    tags: ['enchiladas', 'vegan', 'meksikansk', 'bønner', 'søtpotet', 'belgfrukter', 'ovn'],
    prepTime: 40,
    difficulty: 'enkel',
    leftoverFriendly: true,
    vegetarianAlternative: null,
    recipe: {
      servings: 4,
      steps: [
        'Forvarm ovnen til 190 °C. Skrell og terning søtpotet (500 g) i 1 cm biter. Vend med olje, spisskummen og salt og stek i ovn 20 minutter til mør.',
        'Finhakk løk (1 stk) og hvitløk (2 fedd). Stek i en panne med olje på middels varme i 5 minutter. Tilsett chilipulver (2 ts), spisskummen (1 ts) og røkt paprika (1 ts). Stek 1 minutt.',
        'Tilsett avrent svarte bønner (2 bokser à 400 g) og ristede søtpotetterninger. Bland godt og smak til med salt og limesaft. Dette er fyllet.',
        'Varm tortillalefser (8 stk) i 20 sekunder per side i en tørr panne. Fordel fyllet jevnt på midten av hver lefse og rull fast. Legg sømsiden ned i en ildfast form.',
        'Hell enchilada-saus (1 boks, ca. 400 g) over rullene. Sett formen i ovnen og stek 15–20 minutter til sausen bobler.',
        'Server med avokado i skiver, fersk koriander og limebåter. Eventuelt jalapenos og rødløk på toppen.',
      ],
    },
    shoppingList: [
      { item: 'Svarte bønner (2 bokser)', search: 'svarte bønner boks', amount: '2 × 400 g', estimatedPrice: 32, category: 'Tørrvarer' },
      { item: 'Søtpotet', search: 'søtpotet', amount: '500 g', estimatedPrice: 28, category: 'Frukt/grønt' },
      { item: 'Tortillalefser', search: 'tortilla lefse', amount: '8 stk', estimatedPrice: 28, category: 'Tørrvarer' },
      { item: 'Enchilada-saus', search: 'enchilada saus', amount: '400 g', estimatedPrice: 28, category: 'Tørrvarer' },
      { item: 'Avokado', search: 'avokado', amount: '2 stk', estimatedPrice: 30, category: 'Frukt/grønt' },
    ],
  },

  {
    id: 'gronnsaks-dahl',
    name: 'Grønnsaksdahl med spinat og naanbrød',
    type: 'vegan',
    highProtein: true,
    allergens: ['gluten'],
    tags: ['dahl', 'linser', 'vegan', 'indisk', 'spinat', 'belgfrukter', 'krydret'],
    prepTime: 35,
    difficulty: 'enkel',
    leftoverFriendly: true,
    vegetarianAlternative: null,
    recipe: {
      servings: 4,
      steps: [
        'Finhakk løk (1 stor), hvitløk (4 fedd) og ingefær (3 cm). Ha i en stor gryte med olje (2 ss) på middels varme og stek 6–8 minutter til løken er myk og gyllen.',
        'Tilsett currypulver (2 ts), garam masala (1 ts), gurkemeie (1 ts) og cayennepepper (½ ts). Stek krydderne i 1–2 minutter til de dufter godt.',
        'Skyll røde linser (350 g) og tilsett gryten. Hell over hermetiske tomater (1 boks) og kokosmelk (400 ml). Tilsett grønnsakskraft (4 dl) og rør godt.',
        'Kok opp, skru ned og la småkoke uten lokk i 18–20 minutter under jevnlig omrøring til linsene er møre og sausen tykk. Røde linser løser seg opp og tykner dahlen naturlig.',
        'Tilsett fersk spinat (150 g), rør inn og la falle sammen i 2 minutter. Smak til med limesaft, salt og pepper – dahlen skal være kraftig og aromatisk.',
        'Varm veganske naanbrød (4 stk) i en tørr panne 30 sekunder per side. Server dahlen med naanbrød og fersk koriander over.',
      ],
    },
    shoppingList: [
      { item: 'Røde linser', search: 'røde linser', amount: '350 g', estimatedPrice: 32, category: 'Tørrvarer' },
      { item: 'Kokosmelk', search: 'kokosmelk', amount: '400 ml', estimatedPrice: 22, category: 'Tørrvarer' },
      { item: 'Hermetiske tomater', search: 'hermetiske tomater', amount: '1 boks', estimatedPrice: 12, category: 'Tørrvarer' },
      { item: 'Vegansk naanbrød', search: 'naanbrød', amount: '4 stk', estimatedPrice: 28, category: 'Tørrvarer' },
      { item: 'Fersk spinat', search: 'spinat fersk', amount: '150 g', estimatedPrice: 35, category: 'Frukt/grønt' },
    ],
  },

  {
    id: 'jackfruit-pulled',
    name: 'Pulled jackfruit tacos med avokadokrem',
    type: 'vegan',
    highProtein: false,
    allergens: ['gluten'],
    tags: ['jackfruit', 'taco', 'avokado', 'meksikansk', 'kjøttfri'],
    prepTime: 30,
    difficulty: 'enkel',
    leftoverFriendly: true,
    recipe: {
      servings: 4,
      steps: [
        'Åpne og avrent 2 bokser ung jackfruit i lake. Riv i strimler med gaffel.',
        'Fres løk i olje. Tilsett jackfruit, 1 ts røkt paprika, 1 ts spisskummen, 1 ts chili og 3 ss BBQ-saus. Stek 10 minutter til karamellisert.',
        'Lag avokadokrem: mos 2 avokado med limesaft, hvitløk, salt og pepper.',
        'Varm tortillaer. Fyll med jackfruit, avokadokrem, rød kål, koriander og limesaft.',
      ],
    },
    shoppingList: [
      { item: 'Ung jackfruit (boks)', search: 'jackfruit hermetisk', amount: '2 bokser', estimatedPrice: 55, category: 'Tørrvarer' },
      { item: 'Tortilla', search: 'tortilla hvete', amount: '8 stk', estimatedPrice: 25, category: 'Tørrvarer' },
      { item: 'Avokado', search: 'avokado', amount: '2 stk', estimatedPrice: 30, category: 'Frukt/grønt' },
      { item: 'BBQ-saus', search: 'bbq saus', amount: '3 ss', estimatedPrice: 15, category: 'Tørrvarer' },
      { item: 'Rødkål', search: 'rødkål', amount: '150 g', estimatedPrice: 12, category: 'Frukt/grønt' },
      { item: 'Lime', search: 'lime', amount: '1 stk', estimatedPrice: 8, category: 'Frukt/grønt' },
      { item: 'Koriander', search: 'koriander fersk', amount: '½ bunt', estimatedPrice: 15, category: 'Frukt/grønt' },
    ],
  },

  {
    id: 'blomkal-buffalo',
    name: 'Buffalo-blomkål med vegansk ranch',
    type: 'vegan',
    highProtein: false,
    allergens: ['gluten'],
    tags: ['blomkål', 'buffalo', 'vegansk', 'spicy', 'ovn'],
    prepTime: 35,
    difficulty: 'enkel',
    leftoverFriendly: false,
    recipe: {
      servings: 4,
      steps: [
        'Del blomkål (1 hode) i buketter. Bland med 3 ss hvetemel, 1 dl plantemelk, salt og paprika til en røre. Vend blomkålen i røren.',
        'Stek i ovn på 220°C i 20 minutter til sprø.',
        'Bland 3 ss hot sauce (f.eks. Franks) med 2 ss smeltet vegansk smør. Vend den stekte blomkålen i sausen.',
        'Sett tilbake i ovnen i 5 minutter.',
        'Lag vegansk ranch: bland vegansk rømme/yoghurt med gressløk, dill, hvitløkspulver og sitron.',
        'Server med selleri- og gulrotstaver og ranchen.',
      ],
    },
    shoppingList: [
      { item: 'Blomkål', search: 'blomkål', amount: '1 hode', estimatedPrice: 30, category: 'Frukt/grønt' },
      { item: 'Hot sauce', search: 'hot sauce chili', amount: '3 ss', estimatedPrice: 20, category: 'Tørrvarer' },
      { item: 'Vegansk smør', search: 'vegansk smør plantebasert', amount: '2 ss', estimatedPrice: 15, category: 'Meieri' },
      { item: 'Hvetemel', search: 'hvetemel', amount: '3 ss', estimatedPrice: 5, category: 'Tørrvarer' },
      { item: 'Plantemelk', search: 'havremelk', amount: '1 dl', estimatedPrice: 10, category: 'Meieri' },
      { item: 'Gulrøtter', search: 'gulrøtter', amount: '2 stk', estimatedPrice: 10, category: 'Frukt/grønt' },
      { item: 'Selleri', search: 'selleri stilk', amount: '2 stk', estimatedPrice: 15, category: 'Frukt/grønt' },
    ],
  },

  {
    id: 'miso-gresskar-suppe',
    name: 'Miso- og gresskarssuppe med edamame',
    type: 'vegan',
    highProtein: true,
    allergens: ['gluten', 'soya'],
    tags: ['miso', 'gresskar', 'suppe', 'japansk', 'vegansk'],
    prepTime: 30,
    difficulty: 'enkel',
    leftoverFriendly: true,
    recipe: {
      servings: 4,
      steps: [
        'Skjær butternut gresskar (700 g) i terninger og kok i 8 dl grønnsakskraft til mørt, ca. 15 minutter.',
        'Blend til en silkemyk puré. Rør inn 3 ss hvit miso.',
        'Varm edamame (200 g) i den varme suppa.',
        'Server i boller med sesamfrø, en skvett sesamolje og reddik-skiver.',
      ],
    },
    shoppingList: [
      { item: 'Butternut gresskar', search: 'butternut gresskar', amount: '700 g', estimatedPrice: 38, category: 'Frukt/grønt' },
      { item: 'Hvit miso', search: 'miso paste hvit', amount: '3 ss', estimatedPrice: 35, category: 'Tørrvarer' },
      { item: 'Edamame (fryst)', search: 'edamame', amount: '200 g', estimatedPrice: 28, category: 'Frys' },
      { item: 'Grønnsakskraft', search: 'grønnsakskraft fond', amount: '8 dl', estimatedPrice: 25, category: 'Tørrvarer' },
      { item: 'Sesamfrø', search: 'sesamfrø', amount: '1 ss', estimatedPrice: 10, category: 'Tørrvarer' },
    ],
  },

  {
    id: 'marokkansk-gronnsakstajine',
    name: 'Marokkansk grønnsakstajine med couscous',
    type: 'vegan',
    highProtein: false,
    allergens: ['gluten', 'nøtter'],
    tags: ['tajine', 'marokkansk', 'grønnsaker', 'couscous', 'eksotisk'],
    prepTime: 45,
    difficulty: 'middels',
    leftoverFriendly: true,
    recipe: {
      servings: 4,
      steps: [
        'Fres løk og hvitløk i olje. Tilsett 2 ts ras el hanout, 1 ts koriander og ½ ts kanel.',
        'Tilsett terninget søtpotet (2 stk), kikert (1 boks), hakkede tomater (1 boks) og 2 dl grønnsakskraft.',
        'La putre 25 minutter. Tilsett tørkede aprikoser (50 g) og oliven (100 g) de siste 5 minuttene.',
        'Kok couscous etter pakningsanvisning. Rør inn litt olje og salt.',
        'Server tajinen over couscous med ristede mandelflak og harissa ved siden av.',
      ],
    },
    shoppingList: [
      { item: 'Søtpotet', search: 'søtpotet', amount: '2 stk', estimatedPrice: 30, category: 'Frukt/grønt' },
      { item: 'Kikert (boks)', search: 'kikert hermetisk', amount: '1 boks', estimatedPrice: 15, category: 'Tørrvarer' },
      { item: 'Hakkede tomater', search: 'hakkede tomater hermetisk', amount: '1 boks', estimatedPrice: 15, category: 'Tørrvarer' },
      { item: 'Couscous', search: 'couscous', amount: '300 g', estimatedPrice: 25, category: 'Tørrvarer' },
      { item: 'Ras el hanout', search: 'ras el hanout', amount: '2 ts', estimatedPrice: 20, category: 'Tørrvarer' },
      { item: 'Tørkede aprikoser', search: 'aprikoser tørkede', amount: '50 g', estimatedPrice: 20, category: 'Tørrvarer' },
      { item: 'Mandelflak', search: 'mandelflak', amount: '30 g', estimatedPrice: 18, category: 'Tørrvarer' },
    ],
  },

  {
    id: 'tempeh-stekepanne',
    name: 'Tempeh stir-fry med brokkoli og teriyaki',
    type: 'vegan',
    highProtein: true,
    allergens: ['gluten', 'soya', 'sesam'],
    tags: ['tempeh', 'stir-fry', 'brokkoli', 'teriyaki', 'asiatisk'],
    prepTime: 25,
    difficulty: 'enkel',
    leftoverFriendly: true,
    recipe: {
      servings: 4,
      steps: [
        'Skjær tempeh (300 g) i terninger. Brun på alle sider i olje i 5 minutter.',
        'Tilsett brokkolibuketter (300 g), paprika (1 stk) og vårløk (3 stk). Stek 4 minutter.',
        'Lag teriyaki: bland 4 ss soyasaus, 2 ss honning (eller lønnesirup), 1 ts sesamolje og 1 ts maisstivelse rørt ut i 1 ss vann. Hell over og la koke inn 2 minutter.',
        'Server over dampet jasminris med sesamfrø.',
      ],
    },
    shoppingList: [
      { item: 'Tempeh', search: 'tempeh', amount: '300 g', estimatedPrice: 50, category: 'Kjøtt' },
      { item: 'Brokkoli', search: 'brokkoli', amount: '300 g', estimatedPrice: 25, category: 'Frukt/grønt' },
      { item: 'Rød paprika', search: 'rød paprika', amount: '1 stk', estimatedPrice: 15, category: 'Frukt/grønt' },
      { item: 'Jasminris', search: 'jasminris', amount: '300 g', estimatedPrice: 20, category: 'Tørrvarer' },
      { item: 'Soyasaus', search: 'soyasaus', amount: '4 ss', estimatedPrice: 20, category: 'Tørrvarer' },
      { item: 'Lønnesirup', search: 'lønnesirup', amount: '2 ss', estimatedPrice: 25, category: 'Tørrvarer' },
      { item: 'Sesamfrø', search: 'sesamfrø', amount: '1 ss', estimatedPrice: 10, category: 'Tørrvarer' },
    ],
  },

  {
    id: 'vegansk-bolognese-linse',
    name: 'Vegansk bolognese med valnøtter og linser',
    type: 'vegan',
    highProtein: true,
    allergens: ['gluten', 'nøtter', 'selleri'],
    tags: ['bolognese', 'pasta', 'valnøtter', 'linser', 'italiensk'],
    prepTime: 40,
    difficulty: 'enkel',
    leftoverFriendly: true,
    recipe: {
      servings: 4,
      steps: [
        'Grovhakk valnøtter (80 g) og stek i tørr panne til lett ristet. Sett til side.',
        'Fres løk, gulrot og selleri (1 stk hver) i olivenolje til mykt. Tilsett 3 hvitløkfedd og 2 ss tomatpuré.',
        'Tilsett 2 bokser hakkede tomater, 150 g røde linser og 2 dl grønnsakskraft. La koke 20 minutter.',
        'Rør inn valnøttene og smak til med salt, pepper og oregano.',
        'Server over spaghetti med vegansk parmesan eller gjærflak.',
      ],
    },
    shoppingList: [
      { item: 'Valnøtter', search: 'valnøtter', amount: '80 g', estimatedPrice: 30, category: 'Tørrvarer' },
      { item: 'Røde linser', search: 'røde linser', amount: '150 g', estimatedPrice: 18, category: 'Tørrvarer' },
      { item: 'Hakkede tomater', search: 'hakkede tomater hermetisk', amount: '2 bokser', estimatedPrice: 30, category: 'Tørrvarer' },
      { item: 'Spaghetti', search: 'spaghetti', amount: '400 g', estimatedPrice: 22, category: 'Tørrvarer' },
      { item: 'Gulrot', search: 'gulrøtter', amount: '1 stk', estimatedPrice: 5, category: 'Frukt/grønt' },
      { item: 'Selleri', search: 'selleri stilk', amount: '1 stilk', estimatedPrice: 8, category: 'Frukt/grønt' },
      { item: 'Gjærflak (nutritional yeast)', search: 'gjærflak ernæringsgjær', amount: '2 ss', estimatedPrice: 25, category: 'Tørrvarer' },
    ],
  },

  {
    id: 'sot-potet-karri',
    name: 'Søtpotet og kikertkarry med kokosmjølk',
    type: 'vegan',
    highProtein: true,
    allergens: [],
    tags: ['søtpotet', 'kikert', 'karry', 'kokos', 'enkel'],
    prepTime: 30,
    difficulty: 'enkel',
    leftoverFriendly: true,
    recipe: {
      servings: 4,
      steps: [
        'Fres løk og hvitløk i olje. Tilsett 2 ts currypulver, 1 ts gurkemeie og 1 ts ingefær.',
        'Tilsett terninget søtpotet (2 stk, ca. 500 g) og stek 2 minutter.',
        'Hell i 1 boks kokosmelk, 1 boks kikert (avrent) og 2 dl grønnsakskraft. La putre 20 minutter.',
        'Smak til med limesaft og salt. Tilsett ev. spinat de siste 2 minuttene.',
        'Server med basmatiris og koriander.',
      ],
    },
    shoppingList: [
      { item: 'Søtpotet', search: 'søtpotet', amount: '500 g', estimatedPrice: 35, category: 'Frukt/grønt' },
      { item: 'Kikert (boks)', search: 'kikert hermetisk', amount: '1 boks', estimatedPrice: 15, category: 'Tørrvarer' },
      { item: 'Kokosmelk', search: 'kokosmelk', amount: '1 boks', estimatedPrice: 25, category: 'Tørrvarer' },
      { item: 'Basmatiris', search: 'basmatiris', amount: '300 g', estimatedPrice: 25, category: 'Tørrvarer' },
      { item: 'Currypulver', search: 'karrypulver', amount: '2 ts', estimatedPrice: 15, category: 'Tørrvarer' },
      { item: 'Spinat', search: 'spinat fersk', amount: '100 g', estimatedPrice: 20, category: 'Frukt/grønt' },
      { item: 'Lime', search: 'lime', amount: '1 stk', estimatedPrice: 8, category: 'Frukt/grønt' },
    ],
  },

  {
    id: 'vegansk-fried-rice',
    name: 'Vegansk fried rice med grønnsaker og tofu',
    type: 'vegan',
    highProtein: true,
    allergens: ['gluten', 'soya', 'sesam'],
    tags: ['fried rice', 'tofu', 'grønnsaker', 'asiatisk', 'rask'],
    prepTime: 20,
    difficulty: 'enkel',
    leftoverFriendly: true,
    recipe: {
      servings: 4,
      steps: [
        'Press tofu (400 g) tørr og stek i terninger i olje til gylne, ca. 8 minutter.',
        'Stek frosne grønnsaker (erter, mais, gulrot – 300 g) og vårløk i en wok på høy varme.',
        'Tilsett dagsgammel ris (600 g kokt) og fordel i pannen. Stek 3 minutter uten å røre.',
        'Rør inn 3 ss soyasaus og 1 ss sesamolje. Tilsett tofuen.',
        'Server med chili og ekstra soyasaus.',
      ],
    },
    shoppingList: [
      { item: 'Fast tofu', search: 'tofu fast', amount: '400 g', estimatedPrice: 35, category: 'Kjøtt' },
      { item: 'Kokt ris (dagsgammel)', search: 'jasminris', amount: '300 g (rå)', estimatedPrice: 20, category: 'Tørrvarer' },
      { item: 'Frosne wok-grønnsaker', search: 'wokgrønnsaker frosne', amount: '300 g', estimatedPrice: 25, category: 'Frys' },
      { item: 'Soyasaus', search: 'soyasaus', amount: '3 ss', estimatedPrice: 15, category: 'Tørrvarer' },
      { item: 'Sesamolje', search: 'sesamolje', amount: '1 ss', estimatedPrice: 20, category: 'Tørrvarer' },
      { item: 'Vårløk', search: 'vårløk', amount: '3 stk', estimatedPrice: 10, category: 'Frukt/grønt' },
    ],
  },

  {
    id: 'svarte-bonne-burger',
    name: 'Svarte bønner-burger med avokado',
    type: 'vegan',
    highProtein: true,
    allergens: ['gluten', 'sesam'],
    tags: ['vegansk burger', 'svarte bønner', 'avokado', 'grilling'],
    prepTime: 30,
    difficulty: 'middels',
    leftoverFriendly: false,
    recipe: {
      servings: 4,
      steps: [
        'Avrent og tørk 2 bokser svarte bønner. Mos grovt med en gaffel.',
        'Bland med ½ rødløk (finhakket), 1 ts spisskummen, 1 ts paprika, 2 ss mel, salt og pepper. Form til 4 kaker.',
        'Stek i olje på middels varme, 4 minutter per side til gjennomvarm og sprø.',
        'Lag avokadokrem: mos 2 avokado med limesaft og salt.',
        'Bygg burger: ristede burgerbrød, salat, tomat, bønnekake og avokadokrem.',
      ],
    },
    shoppingList: [
      { item: 'Svarte bønner (boks)', search: 'svarte bønner hermetisk', amount: '2 bokser', estimatedPrice: 30, category: 'Tørrvarer' },
      { item: 'Burgerbrød (veganske)', search: 'hamburgerbrød', amount: '4 stk', estimatedPrice: 25, category: 'Tørrvarer' },
      { item: 'Avokado', search: 'avokado', amount: '2 stk', estimatedPrice: 30, category: 'Frukt/grønt' },
      { item: 'Lime', search: 'lime', amount: '1 stk', estimatedPrice: 8, category: 'Frukt/grønt' },
      { item: 'Tomat', search: 'tomat', amount: '2 stk', estimatedPrice: 15, category: 'Frukt/grønt' },
      { item: 'Rødløk', search: 'rødløk', amount: '½ stk', estimatedPrice: 5, category: 'Frukt/grønt' },
    ],
  },

  {
    id: 'minestrone',
    name: 'Klassisk minestrone med pasta og grønnsaker',
    type: 'vegan',
    highProtein: false,
    allergens: ['gluten', 'selleri'],
    tags: ['minestrone', 'suppe', 'pasta', 'grønnsaker', 'italiensk'],
    prepTime: 35,
    difficulty: 'enkel',
    leftoverFriendly: true,
    recipe: {
      servings: 4,
      steps: [
        'Fres løk, gulrot, selleri og zucchini i olivenolje til myke.',
        'Tilsett 2 fedd hvitløk, 2 bokser hakkede tomater og 1 liter grønnsakskraft. Kok opp.',
        'Tilsett 1 boks cannellini-bønner og 100 g suppepasta. La koke 10 minutter.',
        'Smak til med salt, pepper og frisk basilikum.',
        'Server med god olivenolje dryppet over og ferskt brød.',
      ],
    },
    shoppingList: [
      { item: 'Gulrot', search: 'gulrøtter', amount: '2 stk', estimatedPrice: 10, category: 'Frukt/grønt' },
      { item: 'Selleri', search: 'selleri stilk', amount: '2 stk', estimatedPrice: 15, category: 'Frukt/grønt' },
      { item: 'Zucchini', search: 'zucchini', amount: '1 stk', estimatedPrice: 15, category: 'Frukt/grønt' },
      { item: 'Cannellini-bønner (boks)', search: 'cannellini bønner hermetisk', amount: '1 boks', estimatedPrice: 18, category: 'Tørrvarer' },
      { item: 'Hakkede tomater', search: 'hakkede tomater hermetisk', amount: '2 bokser', estimatedPrice: 30, category: 'Tørrvarer' },
      { item: 'Suppepasta', search: 'suppepasta ditalini', amount: '100 g', estimatedPrice: 18, category: 'Tørrvarer' },
      { item: 'Grønnsakskraft', search: 'grønnsakskraft fond', amount: '1 liter', estimatedPrice: 30, category: 'Tørrvarer' },
    ],
  },

  {
    id: 'falafel-hjemmelaget',
    name: 'Hjemmelagde falafel med tzatziki og pitabrød',
    type: 'vegan',
    highProtein: true,
    allergens: ['gluten', 'sesam'],
    tags: ['falafel', 'kikert', 'pita', 'midtøsten', 'koriander'],
    prepTime: 40,
    difficulty: 'middels',
    leftoverFriendly: true,
    recipe: {
      servings: 4,
      steps: [
        'Bløtlegg tørre kikerter (200 g) natten over. Avrent.',
        'Kjør kikerter, ½ løk, 3 hvitløkfedd, en bunt koriander, 1 ts spisskummen, 1 ts korianderpulver, salt og 2 ss mel i en foodprosessor til en grovkornet masse.',
        'Form til 12–16 kuler. Stek i rikelig olje på middels varme, 3 minutter per side til gyldne.',
        'Lag vegansk tzatziki: bland revet agurk i vegansk yoghurt med hvitløk, dill og salt.',
        'Varm pitabrød. Fyll med salat, tomat, falafel og tzatziki.',
      ],
    },
    shoppingList: [
      { item: 'Tørre kikerter', search: 'kikerter tørre', amount: '200 g', estimatedPrice: 20, category: 'Tørrvarer' },
      { item: 'Pitabrød', search: 'pitabrød', amount: '4 stk', estimatedPrice: 20, category: 'Tørrvarer' },
      { item: 'Vegansk yoghurt naturell', search: 'vegansk yoghurt', amount: '2 dl', estimatedPrice: 25, category: 'Meieri' },
      { item: 'Koriander fersk', search: 'koriander fersk', amount: '1 bunt', estimatedPrice: 18, category: 'Frukt/grønt' },
      { item: 'Agurk', search: 'agurk', amount: '½ stk', estimatedPrice: 10, category: 'Frukt/grønt' },
      { item: 'Tomat', search: 'tomat', amount: '2 stk', estimatedPrice: 15, category: 'Frukt/grønt' },
    ],
  },

  {
    id: 'pasta-pomodoro-vegan',
    name: 'Pasta al pomodoro med ferske tomater',
    type: 'vegan',
    highProtein: false,
    allergens: ['gluten'],
    tags: ['pasta', 'tomat', 'basilikum', 'italiensk', 'enkel'],
    prepTime: 20,
    difficulty: 'enkel',
    leftoverFriendly: false,
    recipe: {
      servings: 4,
      steps: [
        'Kok spaghetti (400 g) al dente. Spar 1 dl pastavann.',
        'Fres 4 hvitløkfedd i rikelig olivenolje på middels varme til gyldne.',
        'Tilsett 500 g knuste ferske tomater (eller 1 boks San Marzano). La koke 10 minutter. Smak til med salt og sukker.',
        'Bland pasta og saus med litt pastavann.',
        'Server med rikelig fersk basilikum, svart pepper og god olivenolje over.',
      ],
    },
    shoppingList: [
      { item: 'Spaghetti', search: 'spaghetti', amount: '400 g', estimatedPrice: 22, category: 'Tørrvarer' },
      { item: 'Ferske tomater (el. San Marzano boks)', search: 'cherrytomater', amount: '500 g', estimatedPrice: 35, category: 'Frukt/grønt' },
      { item: 'Hvitløk', search: 'hvitløk', amount: '4 fedd', estimatedPrice: 5, category: 'Frukt/grønt' },
      { item: 'Fersk basilikum', search: 'basilikum fersk', amount: '1 potte', estimatedPrice: 20, category: 'Frukt/grønt' },
    ],
  },

  {
    id: 'tofu-scramble',
    name: 'Tofu scramble med spinat og paprika',
    type: 'vegan',
    highProtein: true,
    allergens: ['soya', 'gluten'],
    tags: ['tofu', 'scramble', 'egg-erstatning', 'frokost', 'enkel'],
    prepTime: 20,
    difficulty: 'enkel',
    leftoverFriendly: true,
    recipe: {
      servings: 4,
      steps: [
        'Smul fast tofu (400 g) med hendene til en grovkornet masse.',
        'Fres løk og rød paprika (1 stk, terninget) i olje i 3 minutter.',
        'Tilsett tofu og krydre med ½ ts gurkemeie (gir gul farge), 1 ts paprika, 1 ss soyasaus, salt og pepper.',
        'Stek på middels varme i 5–7 minutter under omrøring.',
        'Tilsett spinat (100 g) og rør inn til den faller sammen. Server med toast og cherrytomater.',
      ],
    },
    shoppingList: [
      { item: 'Fast tofu', search: 'tofu fast', amount: '400 g', estimatedPrice: 35, category: 'Kjøtt' },
      { item: 'Rød paprika', search: 'rød paprika', amount: '1 stk', estimatedPrice: 15, category: 'Frukt/grønt' },
      { item: 'Spinat fersk', search: 'spinat fersk', amount: '100 g', estimatedPrice: 20, category: 'Frukt/grønt' },
      { item: 'Soyasaus', search: 'soyasaus', amount: '1 ss', estimatedPrice: 10, category: 'Tørrvarer' },
      { item: 'Gurkemeie', search: 'gurkemeie', amount: '½ ts', estimatedPrice: 10, category: 'Tørrvarer' },
      { item: 'Brød/toast', search: 'sandwichbrød', amount: '8 skiver', estimatedPrice: 25, category: 'Tørrvarer' },
    ],
  },

];
